module.exports = [
  {
  name: 'Damari Longflame',
  race: 'half-elf',
  pronouns: 'she/her',
  title: '',
  class: 'mage',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: 'https://i.pinimg.com/564x/09/78/22/0978220b9223f1b35c803ce6521ab1af.jpg',
  context: 'Sorceress who wards the Ulans (mountains) against Steelclaw the Cruel. She\'s got a long life but it\'s coming to an end, and the world\'s mystical forces can sense this',
  associated: '',
  notes: 'Fiery thimbleweed will extend her life! Unfortunately it only grows on the banks of the Moaning Deep...'
}, {
  name: 'Steelclaw the Cruel',
  race: 'red dragon',
  pronouns: 'he/?',
  title: '',
  class: 'dragon',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: 'https://i.pinimg.com/564x/e9/cc/ff/e9ccff1a0e6050ba12efd4abed820e10.jpg',
  context: '',
  associated: '',
  notes: 'He features somehow in most of Yanoa\'s creation myths... And he\'s been waiting (patiently??) for her wards to weaken, plotting mischief (/evil?) beyond imagining'
}, {
  name: 'Seraphine Dawnstone',
  race: 'human',
  pronouns: 'she/her',
  title: 'Mayor',
  class: 'diplomat',
  description: '',
  trait: 'always smells like mint',
  instinct: 'uncover a hidden truth',
  knack: 'magical awareness',
  aspect: 'beleaguered',
  voice: 'pauses just a bit too long',
  image: 'https://i.pinimg.com/564x/c5/e2/d7/c5e2d7fe2f5d4428ec21457e7b31b659.jpg',
  context: '',
  associated: '',
  notes: ''
}, {
  name: 'Xolag Deepspear',
  race: 'orc',
  pronouns: 'he/him',
  title: 'Captain',
  class: 'fighter',
  description: '',
  trait: 'skin on his arms seems like it\'s recovering from a nasty chemical burn',
  instinct: 'living in brother Klog\'s shadow (champion ratfighter) (civilians wear Klog shirts)',
  knack: 'kindness',
  aspect: 'modest',
  voice: 'overemphasize F',
  image: 'https://i.pinimg.com/564x/b6/5c/83/b65c83cf775700e662b4d3c1aa6735bf.jpg',
  context: 'City Watch',
  associated: 'Shanna Windflare, Kiley Wanderfoot',
  notes: 'hides exotic dancer experience (in orc quarter ofc)'
}, {
  name: 'Shanna Windflare',
  race: 'human',
  pronouns: 'she/her',
  title: 'Lieutenant',
  class: 'rogue',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: 'https://i.pinimg.com/564x/77/56/71/775671112f6a66b6bba808c557ebe5c4.jpg',
  context: 'City Watch',
  associated: 'Xolag Deepspear, Kiley Wanderfoot',
  notes: ''
}, {
  name: 'Kiley Wanderfoot',
  race: 'halfling',
  pronouns: 'she/her',
  title: 'Lieutenant',
  class: 'paladin',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: 'https://i.pinimg.com/564x/77/13/7e/77137ee3e63c41e3be2b8d6dc69a59a4.jpg',
  context: 'City Watch',
  associated: 'Xolag Deepspear, Shanna Windflare',
  notes: ''
}, {
  name: 'Ebba Titanbrew',
  race: 'half-dwarf',
  pronouns: 'she/her',
  title: 'Ms',
  class: '',
  description: 'tavernkeeper at The Grumpy Golem, from a long line of alewives',
  trait: 'ambidextrous',
  instinct: 'to do what must be done',
  knack: 'immunity to poison',
  aspect: 'uses everyone\'s titles always',
  voice: 'higher register',
  image: 'https://pbs.twimg.com/media/DJde5i1WAAAgAcp?format=jpg&name=small',
  context: '',
  associated: '',
  notes: 'The Grumpy Golem. Specialty wine is the King\'s Vintage (implication toward in-house bard). Food special is roasted hazelnuts and fresh apples with a strip of bear jerky and a wedge of ripe cheese. A fight breaks out, between two big strong men. The bartender sighs, and gives each a free drink, separating them.'
}, {
  name: 'Herta Titanbrew',
  race: 'dwarf',
  pronouns: 'she/her',
  title: 'Mrs',
  class: '',
  description: 'from a long line of dwarven alewives. Grew up in Dil Doral',
  trait: 'distinctive tattoo (mostly hidden under sleeve, "Oh, I\'ll tell you when you\'re older, lad/lass)',
  instinct: 'locate a lost thing',
  knack: 'cooking',
  aspect: 'anxious to avoid going home',
  voice: 'overact, overdramatize',
  image: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/600001c3-7f2c-4f7e-88ba-50856e624266/ddvjgra-81d77700-858d-4cfa-94b0-d411b4062b57.jpg/v1/fill/w_786,h_1017,q_70,strp/inn_lady_by_artdeepmind_ddvjgra-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTY1NSIsInBhdGgiOiJcL2ZcLzYwMDAwMWMzLTdmMmMtNGY3ZS04OGJhLTUwODU2ZTYyNDI2NlwvZGR2amdyYS04MWQ3NzcwMC04NThkLTRjZmEtOTRiMC1kNDExYjQwNjJiNTcuanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.TXKhwzof87howK5iG5hFVv_Kcjzw0UmbLOpaCyNiJbA',
  context: '',
  associated: '',
  notes: 'If you catch her in a good enough mood, she may serve you some Old Mill Rye - tastes alright, has a strange aftertaste in the back of your throat of an old sock. It\'s cheap and gets you drunk. / Missed out on the best life has to offer? Look, we don\'t talk about her personal life in Dil Doral. It\'s great place for lots of people.'
}, {
  name: 'King Northwood',
  race: 'owlin (bird person, owl)',
  pronouns: 'he/him',
  title: 'none',
  class: 'bard',
  description: 'bard in residence at the Grumpy Golem',
  trait: 'a smile and laugh that always feel genuinely welcoming',
  instinct: 'to party',
  knack: 'comprehensive local knowledge',
  aspect: 'dignified',
  voice: 'randomly break into song',
  image: 'https://cdna.artstation.com/p/assets/images/images/019/725/792/large/cindy-avelino-bard-2.jpg',
  context: '',
  associated: '',
  notes: 'First name is really Wraith. Listen, his parents were going through a phase, ok?'
}, {
  name: 'Arabella Cloudseeker',
  race: 'human',
  pronouns: 'she/her',
  title: '',
  class: 'rogue',
  description: 'runs the city market',
  trait: 'always wearing only the finest clothing',
  instinct: 'To keep enough order without being a tyrant. To build a nest egg.',
  knack: 'An innate spell (FIGURE OUT).',
  aspect: 'ferengi',
  voice: 'uses sound effects in place of words',
  image: 'https://i.pinimg.com/564x/98/40/73/984073d8eabcc77aacc8d99be603a998.jpg',
  context: '',
  associated: '',
  notes: 'Childhood obsession: horse girl. Ashamed of cowardly runaway brother. People say my hair is my best feature, but it distracts their attention from the rest of me, so I often keep it covered up. Attacked by worgs (p275) in childhood, so goblins go through extra security at the market.'
}, {
  name: 'Divari Simplefire',
  race: 'tiefling',
  pronouns: 'she/her',
  title: '',
  class: 'rogue',
  description: 'runs the underground market',
  trait: 'one long lock of hair that never stays in the ponytail',
  instinct: 'make the best of it',
  knack: 'discerning eye',
  aspect: 'nervous',
  voice: 'speaks too quietly',
  image: 'https://i.pinimg.com/564x/9d/76/18/9d761827da559d9421bdf5f22a07387d.jpg',
  context: '',
  associated: '',
  notes: 'Who has hurt me the most over the years and why do I deserve it? That would be my mother\'s mother; the hag just keeps hanging on! She\'s got such a sharp tongue. I mean, she\'s not wrong; I\'m the first Simplefire in 6 generations without an artistic bone in my body.'
}, {
  name: 'Janos Flatbinder',
  race: 'human',
  pronouns: 'he/him',
  title: '',
  class: 'fighter',
  description: 'head of adventurers guild',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: 'https://i.pinimg.com/564x/61/35/a5/6135a5eed223c8135b52c7bc2ccd139e.jpg',
  context: '',
  associated: '',
  notes: ''
}, {
  name: 'Nysbith Mistspark',
  race: 'dragonborn',
  pronouns: 'she/her',
  title: '',
  class: 'mage',
  description: 'apprenticed to Damari Longflame',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: 'https://i.pinimg.com/564x/71/a0/03/71a003c71fdadbcd3d226ac46efe9df0.jpg',
  context: '',
  associated: '',
  notes: ''
}, {
  name: '',
  race: '',
  pronouns: '',
  title: '',
  class: '',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: '',
  context: '',
  associated: '',
  notes: ''
}, {
  name: '',
  race: '',
  pronouns: '',
  title: '',
  class: '',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: '',
  context: '',
  associated: '',
  notes: ''
}, {
  name: '',
  race: '',
  pronouns: '',
  title: '',
  class: '',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: '',
  context: '',
  associated: '',
  notes: ''
}, {
  name: '',
  race: '',
  pronouns: '',
  title: '',
  class: '',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: '',
  context: '',
  associated: '',
  notes: ''
}, {
  name: '',
  race: '',
  pronouns: '',
  title: '',
  class: '',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: '',
  context: '',
  associated: '',
  notes: ''
}, {
  name: '',
  race: '',
  pronouns: '',
  title: '',
  class: '',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: '',
  context: '',
  associated: '',
  notes: ''
}, {
  name: '',
  race: '',
  pronouns: '',
  title: '',
  class: '',
  description: '',
  trait: '',
  instinct: '',
  knack: '',
  aspect: '',
  voice: '',
  image: '',
  context: '',
  associated: '',
  notes: ''
}]
// instinct: 'recover a lost memory',
  // knack: 'stunning good looks',
  //
