module.exports = ["4-letter words",
"A boy's name",
"A gender-neutral first name",
"A girl's name",
"Acronyms",
"Airlines",
"Alcoholic beverage",
"Alternative profanity",
"Animal noises",
"Animals",
"Animals in books or movies",
"Animated tv shows",
"Appliances",
"Apps",
"Articles of clothing",
"Athletes",
"Authors",
"Awards/ceremonies",
"Baby foods",
"Bad habits",
"Basketball players",
"Beers",
"Birds",
"Board games",
"Bodies of water",
"Book titles",
"Breakfast foods",
"Breeds of dog",
"Cakes",
"Candy",
"Canned foods",
"Capitals",
"Car parts",
"Carbonated drinks",
"Card games",
"Cars (models)",
"Cartoon characters",
"Castles",
"Celebrities",
"Cereals",
"Cheeses",
"Child actors",
"Children's books",
"Children's movies",
"Children’s books",
"Chinese food",
"Chip flavors",
"Chocolates",
"Christmas songs",
"Cities with \"City\" in name",
"Cities with a football team",
"Cleaning products",
"College majors",
"College sports teams",
"Colleges/universities",
"Colors",
"Comedies",
"Comfort foods",
"Comic strip",
"companies",
"Compliments",
"Compound nouns formed with “life”",
"Compound nouns formed with “time”",
"Computer parts",
"Computer programs",
"Condiments and dressings",
"Cooking utensils",
"Cosmetics/toiletries",
"Countries",
"Crimes",
"Dairy products",
"Dances",
"Dangerous animals",
"Desserts",
"Detectives",
"Diet foods",
"Dinosaurs",
"Diseases",
"Disney characters",
"Electronic gadgets",
"Ethnic foods",
"Excuses for being late",
"Fake Bond movies",
"Fake Friends episode titles",
"Fake Hallmark Channel holiday movies",
"Famous actors and actresses",
"Famous duos and trios",
"Famous females",
"Farm animals",
"Fast food places",
"Female athletes",
"Fictional bars or restaurants",
"Fictional characters",
"Fictional pets",
"Fields of science",
"Figures of myth or legend",
"Fish",
"Flowers",
"Food/drinks that are green",
"Foods that are delivery services for other foods",
"Foods you eat raw",
"Football players",
"Footwear",
"Foreign cities",
"Foreign words commonly used in English",
"Frozen foods",
"Fruits",
"Furniture",
"Game terms",
"Games",
"Gibberish words",
"Gifts/presents",
"Gum flavors",
"Halloween costumes",
"Heroes",
"Historic events",
"Historical figures",
"Hobbies",
"Hockey players",
"Holiday activities",
"Holidays",
"Honeymoon spots",
"Hot beverages",
"Household chores",
"Ice cream flavors",
"Insects",
"Insults",
"Internal organs",
"Internet lingo",
"Islands",
"Italian food",
"Items in a backyard",
"Items in a casino",
"Items in a catalog",
"Items in a kitchen",
"Items in a refrigerator",
"Items in a suitcase",
"Items in a vending machine",
"Items in this room",
"Items in your car",
"Items in your glove box",
"Items in your purse/wallet",
"Items you save up to buy",
"Items you take on a road trip",
"Junk food",
"Kinds of candy",
"Kinds of soup",
"Landmarks",
"Languages",
"Leisure activities",
"Literary characters",
"Love songs",
"Magazines",
"Mammals",
"Marvel characters",
"Mascots",
"Math terms",
"Meats",
"Medicine/drugs",
"Menu items",
"Movie prequels",
"Movie sequels (2, 3, 4…)",
"Movie stars",
"Movie titles",
"Muppets",
"Murder weapons",
"Museums",
"Musical instruments",
"Musicians",
"Names used in songs",
"Names used in the bible",
"Nicknames",
"Nicolas Cage movies",
"Nonalcoholic beverages",
"Notorious people",
"Nursery rhymes",
"Occupations",
"Offensive words",
"Olympic events",
"Oxymorons",
"Palindromes",
"Parks",
"Parts of the body",
"People in uniform",
"Periodic table elements",
"Personality traits",
"Pies",
"Pizza toppings",
"Places in Africa",
"Places in Asia",
"Places in Europe",
"Places in South or Central America",
"Places to hang out",
"Podcasts",
"Presidents",
"Princes",
"Princesses",
"Product names",
"Professional sports teams",
"Reasons to call 911",
"Reasons to make a phone call",
"Reasons to quit your job",
"Reasons to take out a loan",
"Recognizable song lyrics",
"Reference books",
"Reptiles/amphibians",
"Restaurants",
"Sales jobs",
"Sandwiches",
"School subjects",
"School supplies",
"Scientists",
"Seafood",
"Ships",
"Slang words",
"Software",
"Something animated",
"Something found at a theme park",
"Something in a backpack",
"Something loud",
"Something people are afraid of",
"Something you can barbeque",
"Something you do on summer vacation",
"Something you keep hidden",
"Something you might find at the doctor's office",
"Something you might find in a bathroom",
"Something you might find in Las Vegas",
"Something you might find under a child's bed",
"Something you're afraid of",
"Song titles",
"Spices/herbs",
"Spicy foods",
"Sports",
"Sports equipment",
"Sports played inside",
"Sports played outdoors",
"Star Wars characters",
"Starbucks orders",
"Stones/gems",
"Store names",
"Street names",
"Terms of endearment",
"Terms of measurement",
"Theme songs",
"Things at a carnival",
"Things at a circus",
"Things at a football game",
"Things at the beach",
"Things Bart Simpson might write on a chalkboard",
"Things found at a bar",
"Things found in a desk",
"Things found in a hospital",
"Things found in a movie theater",
"Things found in New York",
"Things found in the ocean",
"Things found on a map",
"Things in a grocery store",
"Things in a medicine cabinet",
"Things in a park",
"Things in a souvenir shop",
"Things in the sky",
"Things made of metal",
"Things people are allergic to",
"Things people lose",
"Things that are black",
"Things that are cold",
"Things that are flat",
"Things that are hot",
"Things that are made of wood",
"Things that are round",
"Things that are sticky",
"Things that burn",
"Things that can get you fired",
"Things that can kill you",
"Things that fly",
"Things that grow",
"Things that have buttons",
"Things that have spots",
"Things that have stripes",
"Things that have stripes",
"Things that have wheels",
"Things that jump / bounce",
"Things that make you itch",
"Things that make you smile",
"Things that smell bad",
"Things that smell good",
"Things that swim",
"Things that use a remote",
"Things that you wear",
"Things to do at a party",
"Things to do on a date",
"Things to do on a snow day",
"Things with tails",
"Things with wheels",
"Things with wings",
"Things you buy for kids",
"Things you can recycle",
"Things you do at work",
"Things you do every day",
"Things you get in the mail",
"Things you get tickets for",
"Things you make",
"Things you plug in",
"Things you replace",
"Things you save up to buy",
"Things you see at the zoo",
"Things you shouldn’t touch",
"Things you shout",
"Things you sit/on",
"Things you store items in",
"Things you throw away",
"Titles people can have",
"Tools",
"Tourist attractions",
"Toys",
"Trees",
"Tropical locations",
"TV shows",
"TV stars",
"Type of restaurant",
"Types of drink",
"Types of grain",
"Types of weather",
"Unscripted TV shows",
"US cities",
"US states",
"Vacation spots",
"Vegetables",
"Vehicles",
"Video games",
"Villains/monsters",
"Water sports",
"Ways to get from here to there",
"Ways to kill time",
"Weapons",
"Websites",
"Weekend Activities",
"Wines",
"Wireless things",
"Words associated with exercise",
"Words associated with gardening",
"Words associated with math",
"Words associated with money",
"Words associated with outer space",
"Words associated with photography",
"Words associated with the internet",
"Words associated with weather",
"Words associated with winter",
"Words associated with working out",
"Words ending in “-n”",
"Words with double letters",
"World leaders / politicians",
"World records",
/* // my family categories
"Alpaca facts",
"Something in Mom-Mom's house", */
]
