module.exports = ["One very hungry troll. It speaks Common and demands food from the party. If they give the troll food, it leaves them alone.",
"1d2 [redcaps] are tracking the PCs from behind with the intent of attacking them when they camp at night",
"1d4+1 scouts ambush the PC's. Looting their bodies uncovers some gold and a note saying someone has put a bounty on the PCs’ heads.",
"2d6 bandits are waiting along the road. They demand a 25 gp payment from the characters to pass; otherwise, they attack.",
"3 [creatures] are locked into battle with a [bigger creature]. If the PCs help the smaller creature win, they will show them the location of a hidden treasure.",
"A cage containing a [flail snail] has fallen off a caravan and is attacking the caravan workers who come to close to it. The workers will ask the PCs to help them get the cage back in the wagon, rewarding them if they help.",
"A 7+ PER check spots a small chest hidden a tree. It contains a gold ring worth 20gp.",
"A 7+ PER check spots a small chest hidden in a tree. It contains a dead mouse.",
"A 7+ PER check spots caltrops over the floor/ground, which do 1d4 piercing damage to the party if they don’t spot them.",
"A 10+ PER check spots a small chest hidden in a tree. It contains 44gp.",
"A 12+ PER check spots a chest hidden in a tree. It contains a +1 Short Sword.",
"A door stands in the middle of the road. If opened, the frame bursts with confetti, then disappears.",
"A druid is in a field hosting a planting/farming class to promote the care of nature to a group of halflings.",
"A drunk dwarf challenges the strongest looking party member to a wrestling match. Full success on a STR check beats her, and she gives the party member 5gp. Partial success is an honorable draw (maybe she buys the party member a drink). The party member gains a level of exhaustion on a failure.",
"A drunken paladin (knight) riding a horse walks past the PCs. He is rude to them and will provoke them. If they attack him and he escapes, the party will be attacked two days later by a group of 1d4+1 paladins (knights).",
"A dryad runs by, chased by a woodsman (berserker) swinging his axe. If the PCs help the dryad, she rewards them with some treasure. Same goes if they help the woodsman.",
"A dung beetle pushes a ball across the road. If disturbed, it bursts into a smog, doing 1d4 poison damage and leaving the party member poisoned.",
"A dwarf falls out of the sky and splatters in front of the party. No logical source of the dwarf can be seen.",
"A flower girl skips down the path towards the party, but disappears before she reaches them.",
"A group of excited gnomes bounce past the party. If the party is polite to them, one gives them a useless gizmo that makes a chirping noise when wound up.",
"A knight on a warhorse wielding a lance claims the party are dragons in disguise and charges them down.",
"A line of Goblin heads on spikes line the road. A sign written in Goblin next to them says “Traitors of Yeemik”.",
"A local fisherman wanders by, wants to trade.",
"A local gem & jewelery merchant wanders by, wants to trade 500gp worth of loot",
"A local herbalist wanders by, wants to trade. Can also give directions.",
"A local hunter wanders by, wants to trade: Fresh meat, some herbs.",
"A local ranger gives the party directions to their next destination, but he’s an asshole that sends them the wrong way. Increase the journey length.",
"A local ranger gives the party directions to their next destination, shortening their journey.",
"A local wanders by, wants to trade: Basic adventuring equipment.",
"A local wanders by, wants to trade: Five healing potions, 30gp each.",
"A local wanders by, wants to trade: Studded leather armor and basic weapons.",
"A local wanders by, wants to trade: Wood.",
"A local wanders by, wants to trade. Only useful item for sale is a potion of vitality, 25gp.",
"A man is buried in the road up to his neck, with the ground around him undisturbed. If the party helps him, the head pops out the ground and crawls off on spider legs, cackling. If any party members canot pass a roll +WIS, they take 1d10 psychic damage (mixed success means no damage).",
"A man is trapped under a log. If the party helps him, do a straight check. A failure (6-) drops the log and crushes the man. He has nothing of value on him, but the savior gets inspiration if they succeed.",
"A man is trapped under a log. If the party helps him, he disappears - it was an illusion.",
"A mirror image of the party walks towards them, but disappears before reaching them.",
"A mysterious key is found laying in the road. If used on a locked door, roll a d20. A 20 will unlock the door, after which the key is lost.",
"A naked gnome runs across the path, gasps at the party, then runs back. Cannot be pursued.",
"A player (whoever does the roll) trips over, takes 1d4 bludgeoning damage.",
"A random skeleton walks by carrying a mop. It asks the PCs to buy it a drink at the next village.",
"A road sign points back to wherever the party came from, but is otherwise useless.",
"A satyr offers to show the party a magical wonder, for a price. If they go there, there are 1d4+1 additional satyrs waiting there to jump them. The satyrs are drunks that just ran out of wine.",
"A skeleton riding on a skeleton horse, that only appears at night.",
"A stranger asks for directions from the party to the last town they left. If they help him, he gives them 1d6x10 gold when they next appear in town, if ever.",
"A stranger asks to be escorted to a town, but gives the party nothing for doing it.",
"A stranger asks to be escorted to the nearest town. If the party agrees, the stranger gives them 100gp upon delivery.",
"A stranger on the road tells each PC to repent of their sins. He knows details.",
"A strong storm picks up.",
"A succubus disguised as a regular woman is roadside by a broken cart. She gets their help fixing the wagon, and attempts to charm one of the PCs and give him a kiss (draining kiss).",
"A thick fog prevents travel for the rest of the day.",
"A trail of small *oddly* realistic animal parts scatter the ground. Should the party make too much noise, they hear a squawk and see 1d4 cockatrices emerging from a hole nearby.",
"A traveling chef is passing through a town and is looking for adventurers to search for exotic creatures and herbs the rarer the animal the more the chef will pay.",
"A traveling merchant (thug) in a wagon drops a rug as they pass by the PCs. It's actually a rug of smothering and the merchant is actually a highway robber preying on good-nature people that try to return the rug to him.",
"A vagrant asks for food. Nothing happens if they give him some.",
"A vagrant asks for money. If they give him some, they get back triple what they give.",
"A vagrant asks for money. Nothing happens if they give him some.",
"A well-known serial killer (use the spy stat block) who broke out of prison passes by the party wearing a hooded cloak trying to disguise himself. The man is acting very oddly. If apprehended, the PCs could earn a lot of money. The PCs only recognize the serial killer on a 10+ INT roll.",
"An [oni] and a hag are in the middle of the road, discussing who is prettier. They ask the party to help settle the problem.",
"An acolyte con artist that wants to gamble with the adventurers. She’s down on her luck and needs to pay for a mistake she made to gain entry back into her religious order.",
"An Ancient Gold Dragon approaches the party, disguised as a noblewoman. She jests with the party for awhile before moving on. If provoked, she will perform a show of strength to intimidate the party.",
"An arrow strikes a nearby tree, with a note attached to it. The note reads “You are a fool for looking!” No source of the arrow can be found.",
"An enormous dragon flies overhead.",
"Omen: A beautiful white horse dashes past the party and disappears.",
"Omen: A black dog runs across the path.",
"Omen: A lone yellow flower is growing in the middle of the path.",
"Omen: A pool of blood.",
"Omen: A roll of thunder.",
"Omen: A shadow drifts over the party.",
"Omen: The earth shakes briefly.",
"Omen: The sun bursts through an overclouded sky.",
"Party encounters a bard, who sings a song of battle. The next combat encounter grants double xp reward.",
"Party encounters a bard, who sings a song of good health. Gain 1d8 temporary hitpoints.",
"Party encounters a bard, who sings a song of healing. Regain up to half your max HP.",
"Party encounters a bard, who sings a song of heroics. 1d6 party members gain inspiration.",
"Party encounters a bard, who sings a song of misery. All party members with inspiration lose it.",
"Party encounters a bard, who sings a song of pain. Lose 1d8 HP (after the bard has long since passed).",
"Party encounters a bard, who sings a song of rest. Lose any debuffs.",
"Party encounters a bard, who sings a song of storms. A storm starts and forces the party to stop for the rest of the day.",
"Party encounters a bard, who sings a song. Nothing special happens.",
"Party encounters a mysterious old lady, who asks them a riddle: I have a tail, but no body. I have a head, but no brain. What am I? (coins, 50gp reward)",
"Party encounters a mysterious old man, who asks them a riddle: Two bodies have I, though both joined in one. The more still I stand, the quicker I run. What am I? (An hourglass. Time slows down if they get it, and immediately skips to night if they don’t)",
"Party encounters a púka (humanoid bunny creature), who asks them a riddle: What kind of ear cannot hear? (An ear of corn. Potion of Cure Silence, everyone deafened if they don’t get it) (https://bit.ly/35GneGR)",
"Party encounters a sphinx, who asks them a riddle: My rivers are dry, my forests have no trees, my towns are flat and empty, and my roads cannot be walked on. What am I? (A map. The party's journey is shortened)",
"Patches of poisonous plants grow in a field of plants that look very similar. The plants can be used as an ingredient to make potions of poison, but if touched they poison a character for 1d4 hours if they fail a 10+ CON saving throw.",
"PC's encounter a patrol of 1d4+1 hostile hobgoblins. Killing them might bring the rest of the hobgoblin hoard down on the PC's.",
"The party are being stalked by 1d6+2 wolves. If the party succeeds on a 10+ PER check, they notice the wolves. Otherwise, when the wolves attack, they gain surprise.",
"The party catches up with and overtakes a slow-walking farmer, bickering with his wife. They know nothing useful.",
"The party comes across 3 wolves hunting a deer. They can either watch nature take its course or save the victim.",
"The party finds 100gp in a chest in the middle of the road.",
"The party finds a random cow. No amount of investigation reveals anything of significance about the cow or where it came from.",
"The party finds a roadside shrine to the god of travel. On it is an offering of food and a few coins. If the PCs take anything from the shrine, they have \"bad luck\" for the day.",
"The party finds a sword in a stone. A 10+ STR check pulls it out. It is a +1 Longsword.",
"The party finds the tracks of an Owlbear going across the road (flat 7+).",
"The party finds the tracks of wolves going across the path (flat 7+).",
"The party notices that they are being followed by a bush, which runs into the forest when they attempt to investigate. If they pursue, they find a goblin, who throws a gold coin at them to make them go away.",
"The PCs encounter a bear stuck in a hunters trap. Do they let him go? Kill and take the spoils? Let him be?",
"The PCs meet a friendly, medium-sized, young dire wolf that is famished. Feeding it and making a 10+ WIS check makes the group a new friend.",
"The players encounter a group of more experienced adventurers heading in the other direction. If the players are polite, they are given some healing potions.",
"The players find an encampment of well armed, friendly humans. They may stay the night here and avoid a random encounter for the night.",
"There is a plate of food, on a table, in the middle of the road. That’s it.",
"There is an illusionary camp with a warm fire and a pile of food and supplies that can trick/charm players to come close. If they do, 1d3 [quicklings] attacks the PCs.",
"There is an unusually vocal chorus of birdsong. Druids, Hunters, Clerics gain inspiration.",
"They encounter an owlbear attacking a small caravan of four wealthy nobles with 1d6+2 guards. If the PCs help defeat the owlbear, the nobles give them a medal worth 50 gp that gives them street cred in any nearby city.",
"Trap: A cupcake lays in the middle of the road. If the party approaches, they trigger a pitfall into spikes. 3d6 piercing damage.",
"Trap: 7+ DEX check or 1d6 bludgeoning damage, pit fall.",
"Trap: 7+ PER check or snared, 1d6 bludgeoning damage if cut loose without landing being factored in.",
"Trap: 10+ DEX check or 1d8 bludgeoning damage, pit fall.",
"Trap: 10+ PER check or snared, 1d6 bludgeoning damage if cut loose without landing being factored in.",
"Trap: 10+ PER check or whole party snared by net, roll combat encounter.",
"Trap: 12+ DEX check or 1d12 bludgeoning damage, pit fall.",
"Trap: 12+ PER check or snared, 1d6 bludgeoning damage if cut loose without landing being factored in.",
"Trap: Door in the middle of the path. If opened, a Hobgoblin is on the other side and gets a surprise attack. If walked around, the Hobgoblin flees.",
"Trap: Magic rune (10+ PER to detect) triggers, paralyzing party. Roll for a combat encounter.",
"Two hooded figures are leading a third bound figure along the road. If questioned, they claim the person is a captured criminal. The two hooded figures are actually 1 Cult Fanatic and 1 Cultist taking a innocent person to be sacrificed.",
"A pigeon arrives with a note from your ex. Yes, THAT ex. Requesting your aid. Desperately.",
"A frog hops onto the road claiming to be a prince. 6- just a frog (ventriloquist behind tree), kisser slimy. 7-9 human but broke. 10+ truly a prince, v grateful (player's choice: marriage, great job in kingdom, send money to home, pick up money at kingdom).",
"Merchants taking chained orc girl to town for jail/slavery. If they rescue her, she kills the next friendly npc they meet.",
"Party encounters merchants taking chained orc girl to town for jail/slavery. If they rescue her, she kills the next friendly npc they meet.",
"The party sees a potion bottle sticking out from under a tree root. If they open it to investigate, a genie pops out EITHER 1) offering them beauty beyond their wildest dreams OR 2) exactly one wish (something they can't see changed here and now) (get Daniel's help to evil genie this ofc)"]
