module.exports = [
// "Insects",
// "Insects",
// "Birds",
// "Birds",
// "Scavengers",
// "Scavengers",
"Lightning",
"Lightning",
"Nobility",
"Nobility",
"Commoners",
"Commoners",
"Foreigners",
"Foreigners",
"Boys who have yet to kill",
"Boys who have yet to kill",
"Menstruating women",
"Post-menopausal women",
"Post-menopausal women",
"Anyone who has killed since the last solstice",
"Anyone who has killed since the last full moon",
"Anyone who has killed since the last rain storm",
"Anyone who has killed since the last harvest",
"The kinship moiety opposite those holding the rites (eg, in a patrilineal culture, the priest’s mother’s brothers)",
"Anyone who was born with a cleft lip",
"Anyone who was born to a widow",
"Anyone who was born during the new moon",
"Flowers",
"Flowers",
"Mushrooms",
"Mushrooms",
"Meat",
"Meat",
"Root vegetables",
"Root vegetables",
"Specific colors",
"Specific colors",
"Specific cooked dish (e.g., chili, bread)",
"Specific cooked dish (e.g., chili, bread)",
// "A deity worshiped by a party member"
]
