module.exports = ["Orgy",
"Human sacrifice: Strangulation",
"Human sacrifice: Immolation",
"Human sacrifice: Ritual combat",
"Human sacrifice: Heart removal",
"Animal sacrifice: Cattle",
"Animal sacrifice: Goats or sheep",
"Animal sacrifice: Horses",
"Animal sacrifice: Doves or chickens",
"Animal sacrifice: Birds of prey",
"Animal sacrifice: Dogs or wolves",
"Feast",
"Feast",
"Feast",
"Bonfire of trade goods",
"Fasting",
"Hallucinogenic drugs",
"Self-torture",
"Poetry recital",
"Athletic games",
"Cleaning up the town",
"Singing sacred songs",
"Utter silence",
"Music and dancing",
"Nakedness",
"Mystery play",
"Tattooing",
"Shaving all hair",
"Elaborate costumes",
"Pranks",
"Parade",
"Light mini lanterns that float up into the sky",
"Ritual washing"
]
