module.exports = ["An hour",
"An hour",
"An hour",
"Several hours",
"Several hours",
"Several hours",
"Several hours",
"Several hours",
"Several hours",
"A day and a night",
"A day and a night",
"Three days",
"A week",
"All month",
"Until sunrise",
"Until sunrise",
"Until sunrise",
"Until sunrise"]
