module.exports = [
  "Head, Shoulders, Knees, and Toes: Run by a mysterious wizard, this shop it only sells human appendages.",
  "Morticia's morgue: will hide and remove bodies, perform autopsies etc., in return for rare bodies/monster parts.",
  "Dark Arts & Melted Hearts: Your typical 'Dark Arts' type store, but complete with a tavern type meeting area that regularly provides a speed dating-esque environment for undesirables, villians, & general ne'er-do-wells. Everyone deserves a shot a love right?",
  "Whispers & Secrets: The only goods bought and sold here are rumors, secrets, other generally unknown information. You cannot pay with traditional currency, must offer hidden information of your own to barter with. Use either an unbiased magical system (such as speaking your secret into a glass jar, putting the lid on placing upon a magical scale that determines its weight/value), or for more interesting roleplaying opportunities have a totally biased shopkeep the players can haggle with or try and persuade.",
  "Proctor & Son's Deadly Traps: More a small dungeon than a store, the ceiling to floor to finally the basement is covered in traps. You must survive long enough to actually disarm and then purchase your chosen traps. It used to be a family business but that didn't last for very long.",
  "Ayesha's Insult Emporium: The store's name, in simple black lettering, is all that implies what lies inside. A friendly middle-aged woman (presumably Ayesha) wearing a sari greets customers entering this store's antechamber with a sharp personal insult. Anyone who takes great offense to the insult is teleported out of the shop and can't reenter. However, those who accept it in good spirit will be led by Ayesha to the main room, which contains shelves and cabinets filled with scrolls, books, and scraps of paper containing some of the most brilliant, sought-after and mind-bending insults to ever have been uttered or penned.",
  "Alethra's Tear Shop: A medium-sized store with shelves full of tiny bottles of tears, which are all carefully labeled with the date the tears were shed, the name and race of the being that shed them, and the reason they were shed. Run by a middle-aged woman named Alethera, an unusually cheerful person who is as eager to buy new tears as she is to sell them. Alethera is especially interested in the tears of adventures and famous people.",
  "Darvin's Dandy Dolls: A shop with shelves full of dolls, many of them resemble important political figures of the region. It is rumored that some of the dolls have power over the people they represent.",
  "Sprog's Spirits: A dark shop run by a well tempered and grim half orc. It's shelves are filled with bottles that Sprog claims hold the spirits of the dead.",
  "Magroma's Jewelry: A 'jewelry store' run by an old woman where all of the jewelry is made out of the polished bones of various creatures, some of them quite exotic.",
  "Clara's Haberdashery: a half-orc woman makes and sells fashionable hats to normal patrons, but sells magical hats on the black market. Her hats are imbued with special abilities by using rare and wonderful items. She's an artist to her core and she'll try to accommodate your request, but at the end of the day, it's her final word. Imagine wild versions of hats you know, precursors to hats we have now, but much more ornate and fanciful.",
  "People, People!: It's a shop where you can hire people. There's different races and strengths of people for different prices. You can hire a commoner for 1 gold as usual, but there's a few stronger people, or twin halflings that come as a bundle, or an old lady that's very expensive. There's not usually shops where you can easily hire people. Here one is.",
  "Dundragon Family Goods: This store appears to be an average general goods store run by a small family of three, a father, a mother, and a daughter, but any local criminal will know that 'Dundragon Family Goods' is actually the best place to find illegal supplies without attracting attention, as the whole family knows thieves cant.",
  "Madame Tralancet's Veritable Shop of Disguises and Costumes for the Modern Journeyman: She has an enormous selection of suspiciously cheap costumes, disguise kits, wigs, and other fake parts. She has seven drawers bulging with moustaches alone.",
  "Doctor Nehantil's Reputable Establishment: In a rundown shack in a bad part of town, a half-orc woman runs reception. Give her your appointment card, and she'll tear off the planks from the back wall where you can meet Dr. Nehantil, a 'physician' with cheap prices and even cheaper services, no questions asked.",
  "Kesheki's Weapon Shop: A store in the darkest corner of the town run by a curiously well-mannered female gnoll, Kesheki. The shop sells all kinds of the most exotic and vicious weapons imaginable. The only currency Kesheki will accept are the scalps of humanoids; the stronger the creature the scalp was taken from the more valuable the scalp is.",
  "Skeleton Shop: A large underground complex selling all kinds of animate skeletal animals. The owner is a jovial skeleton who only accepts currency taken by force, without the previous owner's consent."

]
