module.exports = ["Roper",
  "Butcher",
  "Silverstring",
  "Silentfoot",
  "Chubb",
  "Wolfbloom",
  "Spiritorb",
  "Oceanhand",
  // "Icedane",
  "Cragcaller",
  "Golddrifter",
  // "Woodbinder",
  // "Leafpeak",
  "Spiderflow",
  "Truthstrider",
  "Bloodthorn",
  "Clanstalker",
  "Fogcrest",
  // "Mildbash",
  "Rapidwater",
  "Paleripper",
  // "Frosttrack",
  // "Fireshine",
  "Battlerock",
  "Forestbone",
  // "Dustscar",
  "Skywater",
  "Clawwalker",
  "Tusktail",
  "Snakebreeze",
  "Blazesteel",
  // "Fernfury",
  "Crowspear",
  "Humblelance",
  "Stoneash",
  "Flintcrag",
  "Flatash",
  // "Mossglory",
  "Grassbleeder",
  // "Sunleaf",
  // "Moonleaf",
  "Lightforce",
  // "Silentswift",
  "Chesthell",
  "Havenscribe",
  "Ferngaze",
  "Emberwhisk",
  "Shadowbow",
  // "Flatbinder",
  "Forescar",
  "Icespell",
  "Lunaspark",
  "Silversworn",
  "Windless",
  "Wheatbone",
  // "Heartswallow",
  "Starbeam",
  "Serpentless",
  // "Redroot",
  "Havenkeeper",
  "Wildgrip",
  "Amberbeam",
  // "Deepspear",
  "Grayeyes",
  "Greengaze",
  "Treesoar",
  // "Cloudseeker",
  "Horsebloom",
  "Truestalker",
  // "Regalbreath",
  "Dragoncaller",
  "Cliffcloud",
  "Highhelm",
  "Grizzlyhunter",
  // "Dreamlance",
  "Greenfist",
  "Barleycaller",
  "Truedancer",
  "Bonekeep",
  // "Dragonsky",
  "Clawbluff",
  "Fullmoon",
  "Dragonblade",
  "Snakehide",
  "Sharpsinger",
  "Redshout",
  "Nosedrifter",
  "Solidstrider",
  "Laughingblade",
  "Springsoar",
  "Dirgeweaver",
  "Palesky",
  "Glorygrove",
  "Simplefire",
  "Sharpkiller",
  "Crystalmore",
  "Moltenflame",
  // "Starrunner",
  "Mournbloom",
  "Leafpelt",
  "Greatroar",
  // "Mistheart",
  "Hazearm",
  "Shieldkeep",
  // "Ambertalon",
  // "Hawkscar",
  "Dirgechewer",
  "Hellflare",
  "Truthcleaver",
  "Crystalgrip",
  "Gloomflaw",
  // "Hallowtrapper",
  "Voidblood",
  "Plainfollower",
  "Lightfang",
  "Bramblepelt",
  "Jayfeather",
  // "Nightshade",
  "Nightriver",
  "Nightfire",
  "Nighthunter",
  "Shadowskin",
  "Shadowrose",
  // "Shadowbird",
  "Shadowstorm",
  "Nightwing",
  // "Lilyheart",
  "Whiteshadow",
  "Whiteclaw",
  "Whiterose",
  "Whitethorn",
  "Rosefall",
  "Thornprick",
  "Cobrastrike",
  // "Bramblesong",
  "Brambleprick",
  "Briarsong",
  "Thornwing",
  // "Sunfern",
  "Sanddust",
  "Sandpelt",
  "Sandmist",
  "Tabbyclaw",
  "Sparrowflight",
  "Troutleap",
  // "Morningdew",
  "Applewood",
  "Mousefang",
  "Wyvernmaw",
  "Serpentbinder",
  "Wheatglade",
  "Stagmaw",
  "Bramblepelt",
  "Simplefire"]
