module.exports = [
  "French accent",
  "nasal",
  "'hw' e.g., 'hwhat is that'",
  "stutter",
  "batman",
  // "overact, overdramatize",
  "james t kirk",
  "third person",
  "lower register",
  // "higher register",
  "whispery",
  "speak into a glass",
  "clenched teeth",
  "angry new yorker",
  "overemphasize A",
  "overemphasize B",
  "overemphasize C/K",
  "overemphasize D",
  "overemphasize E",
  // "overemphasize F",
  "overemphasize G",
  "overemphasize H",
  "overemphasize I",
  "overemphasize J",
  "overemphasize C/K",
  "overemphasize L",
  "overemphasize M",
  "overemphasize N",
  "overemphasize O",
  "overemphasize P",
  "overemphasize R",
  "overemphasize S (hissssssssss)",
  "overemphasize T",
  "overemphasize U",
  "overemphasize V",
  "overemphasize W",
  "overemphasize X",
  "overemphasize Z",
  // "randomly break into song",
  "horrible smoker\'s cough",
  "clears throat extra",
  "repeats every question asked of them before answering",
  "hmmmms when thinking",
  "speaks loudly (hard of hearing)",
  "speaks very quickly, nervous talker",
  "object subject switch (Yoda)",
  "upward inflection at every sentence (like a question)",
  "plain speaking style",
  "elevated/educated speaking style",
  "uses a billion purple adjectives",
  "pitch all over the place",
  // "pauses just a bit too long",
  "voice husky / hoarse",
  "uses very few / minimum words",
  // "speaks too quietly",
  "ghost of Xmas present (a large absent-minded spirit)",
  "drops names (Tahani)",
  "drops names (like my sister always says...)",
  "forgets thread mid-story",
  "easily distracted",
  "lisps (th for s) (igors)",
  "lisps (sh for th)",
  "lisps (w for l)",
  "lisps (w for v)",
  "neanderthal (one-syllable words)",
  "lots of ummm, uhhh, well (filler words)",
  // "uses sound effects in place of words",
  "matter-of-fact",
  "monotone"]
