module.exports = [
  "bad acne all over their face.",
"their eyes squinted like they are looking into a bright light.",
"has one more tattoo every time they show up in the story. This is never addressed by any other NPC who could know him.",
"luscious, carbon-black, long hair that extents beyond their own height. It is keep in a long braid. They haven’t cut it since birth.",
"a face only a mother could love.",
"a body build that appears both muscular and lanky.",
"a thin, delicate build.",
"missing one or more teeth.",
"large bushy eyebrows.",
"a distinctive military tattoo.",
"fingers that are just a little too long. Maybe they have a bit of fae blood in them?",
"The skin on the arms seems like it's recovering from a nasty chemical burn.",
"skin is covered in battle scars.",
"ambidextrous.",
"buck-teeth.",
"an unkempt and slobbish look.",
"incredibly cold hands.",
"a distinctive accent that places them from a certain country or region.",
"a hunchback.",
"a hissing voice.",
"watery eyes.",
"speaks very fast-paced.",
"a distinctive cult tattoo.",
"a high-pitched, squeaky voice.",
"a large scar across their chin.",
"has a mechanical replacement for a few fingers/hand/arm.",
"gorgeous eyes.",
"always wearing only the finest clothing.",
"a patch of discolored skin around an old scar. They were poisoned by (someone, something) long ago. They recovered, but it left its mark.",
"always has some red stain on their hands. Surely its just tomato sauce... right?",
"always smells like farm animals.",
"a peg leg.",
"6 fingers instead of 5 on each hand.",
"INCREDIBLY beautiful. People often do double-takes of them as they walk by.",
"a deep, baritone voice.",
"smells TERRIBLE.",
"a beehive hair style.",
"has hair changing color according to their mood following an accident involving wild magic.",
"dresses like a slob, and tends to wear the same clothes for weeks.",
"missing 1d8 fingers from a farming accident.",
"missing a finger in a kitchen accident.",
"a distinctive slave tattoo.",
"an abormally long nose.",
"a limp due to a magical mishap (they were practicing a specific spell that backfired).",
"wears torn, dirty clothing.",
"a monk haircut.",
"never looks anyone in the eyes.",
"really accentuated cheekbones, and hollow cheeks.",
"lots of freckles.",
"noticeably crooked teeth. They try to hide their mouth while speaking.",
"a tiny nose.",
"a deep, resonating voice.",
"freckles on their face positioned in a way to resemble runes.",
"huge bulging muscles.",
"missing their tongue, making them a mute.",
"happy, warm eyes.",
"bald (naturally bald, shaved head).",
"exceptionally short for their species.",
"a samurai bun hair style.",
"cross-eyed.",
"an allergy that causes them to sneeze a lot.",
"is constantly hunched over. If they stretched upwards, they'd gain a good foot in height.",
"has a thick, furry unibrow.",
"a tattoo of a mermaid on their arm.",
"accident prone, keeps tripping on cobblestones, spill drinks and food on themselves and others, falls down stairs, but never any fatal injuries.",
"always smells like incense.",
"watchful eyes.",
"the most glorious mustache.",
"an anchor tattoo.",
"acne scars on their face.",
"sleepy eyes.",
"a skull tattoo.",
"cold, calculating eyes.",
"a mouth that hangs open.",
"a distinctive sailing tattoo.",
"a large scar over their right eye. Every time they are asked about it, their story changes on how they got it.",
"always seems to be covered in dirt from working in the (fields, mines, mud)",
"dreadlocks.",
"wild eyes.",
"over-sized ears.",
"always smells like fish.",
"a smile and laugh that always feel genuinely welcoming.",
"clearly had their nose broken numerous times.",
"elaborately pierced ears.",
"fashionable, hip clothing.",
"dry, cracked lips.",
"appears to have both some features common in the current nation's population, and some features from a population that's many many miles away.",
"wears an ear trumpet to hear.",
"pointy ears.",
"rotund.",
"a dagger tattoo.",
"rotting teeth.",
"constantly biting their nails out of nervousness.",
"a distinctive tribal tattoo.",
"long, braided hair.",
"breath is visible as if it always is a cold winters day around them.",
"really long, really sharp nails. Usually used in “boogie man” stories to scare the local children.",
"piercing eyes.",
"always smells of baked bread.",
"skinny as a rail."
]
