module.exports = ["belligerent",
  "self-important",
  "over-polite",
  "fearful",
  "paranoid",
  "delighted",
  "overly serious",
  "bubbly",
  "Knows Everything",
  // "exasperated",
  "snobby",
  // "Ferengi",
  "superior",
  "morosely depressed (Eeyore)",
  "arrogant",
  "hiding something",
  "posh",
  "Popeye",
  "rude",
  "obliviously selfish",
  "flamboyant",
  "Arthur, King of the Britons",
  // "uses everyone's titles always",
  "never uses anyone's title",
  "sniffles a lot",
  "dictatorial",
  "nervous",
  "pompous",
  // "unassuming",
  "gruff",
  "lecherous",
  "jumpy, obsequious (abused)",
  "coward",
  "crafty, cunning",
  "ambitious",
  "always complaining about the weather",
  "always complaining about kids these days",
  "always complaining about their footwear",
  "always complaining about the low-quality food or drink",
  "always complaining about daughter's idiot fiancé",
  "always complaining about [race that makes sense]",
  "always complaining about ",
  "always complaining about ",
  "always complaining about ",
  // "waxes nostalgic about food in ______",
  "waxes nostalgic about the adventures of their youth",
  "waxes nostalgic about past lovers",
  "waxes nostalgic about ",
  "insecure about being bad at magic",
  "living in parent's shadow",
  // "living in sibling's shadow",
  "too busy right now",
  "having the unluckiest day",
  "extremely generous (just won jackpot or suchlike)",
  "cowboy",
  "enthusiastic",
  "mean",
  "jealous",
  "compassionate / do-gooder",
  "warmongering",
  "studious",
  "weak-willed",
  "gives everyone familiar nicknames",
  "conspiratorial",
  // "anxious to avoid going home",
  "dreadfully bored",
  "interrupts others",
  "Jason Mendoza",
  "Derek (Good Place)",
  "I don't try new things",
  "Self-Critical",
  "Observant",
  // "Dignified",
  "Patient",
  "Warm",
  "Cooperative",
  "Dutiful",
  // "Modest",
  "Workaholic",
  "Humourless",
  "Overconfident",
  "Predictable",
  "Hedonistic",
  "Reckless",
  "Stubborn",
  "Senile",
  "Beleaguered",
  "Incompetent yet confident"]
