module.exports = ["Funerary",
"Astronomical (eg, solstice, equinox, new moon)",
"Agrarian (eg, harvest, planting)",
"Wedding",
"Coming of age",
"Diplomatic (eg, signing a peace treaty)",
"The slaying of a great beast (thanks for a big meal)",
"The slaying of a great beast (that has been plaguing the town)",
"[Important person]'s birthday",
"Oldest townsperson's birthday",
"Founding day",
"Anniversary of great victory",
"In preparation of felling a great tree",
"In petition for fertility"]
