module.exports = [
  "grow scales on torso (armor +1)",
  "eyes become segmented bug eyes",
  "inspiration",
  "stoneskin",
  "healing (labeled)",
  "instant rage (5 temp HP, +4 STR, +4 CON, upgrade damage die, advantage on battle rolls)",
  "cantrip: detect alignment",
  "cantrip: cure light wounds (1d8)",
  "cantrip: speak with dead (3 questions)",
  "Poison: Oil of Tagit. Dangerous, applied, 15 coins, 0 weight. The target falls into a light sleep.",
  "Poison: Bloodweed. Dangerous, touch, 12 coins, 0 weight. Until cured, all damage the person inflicts is -1d4.",
  "Poison: Goldenroot. Dangerous, applied, 20 coins, 0 weight. The target treats the next creature they see as a trusted ally, until proven otherwise.",
  "Poison: Serpent’s Tears. Dangerous, touch, 10 coins, 0 weight. Anyone dealing damage against the target rolls with advantage.",
  "Antitoxin. 10 coins, 0 weight. When you drink antitoxin, you’re cured of one poison affecting you.",
  "You grow feathers all over your body.",
  "You feel your body begin to change! You are turned into a tiny frog for 1d4 days.",
  "You fall in love with the first living thing you see.",
  "Your skin begins to turn a sickly green, and you gain the ability to breathe underwater for 1d4 hours. You also lose the ability to breathe outside of water for the time limit!",
  "You grow gills on your neck. You can breathe underwater for 1d4 hours.",
  "You can only speak in lies for 1d4 days.",
  "Your skin begins to glow, creating a 25ft. aura of light around you.",
  "You forget how to read for 1d4 days.",
  "You gain the effects of gaseous form for 1d4 hours.",
  "You gain a vague, mystical vision of the future. (https://www.dndspeak.com/2020/01/29/100-prophetic-dreams-that-mean-nothing/)",
  "Your hair turns the color of the potion you drank.",
  "You feel your tongue begin to twist. You can only speak in rhyme for 1d4 hours.",
  "You lose your shadow permanently.",
  "You begin to hover one foot off the ground for 1d4 hours.",
  "You suddenly feel another arm growing out of your back. This third arm lasts for 1d4 days before it falls off. It functions as a normal arm.",
  "You can speak to animals for 1d4 hours.",
  "You gain 1d10 hit points each round for 1d4 rounds.",
  "Your fingers become completely flaccid for 1d4 hours. You cannot hold anything in your hands.",
  "All tattoos on your body vanish.",
  "Spiked vines begin growing out of your body for 1d4 days. If a creature touches you, they take 1d4 damage.",
  "You grow a third eye in the center of your forehead, increasing your perception skill by 2.",
  "You are instantly resurrected if you are killed within 24 hours of drinking this potion.",
  "You become extremely physically ugly for 1d4 hours, losing 2 points of CHA.",
  "Your size shrinks by 1d4 feet for 1d4 hours.",
  "Your skin begins to harden at an alarming rate. You are turned to stone for 1d4 hours.",
  "Your skin turns to metal for 1d4 hours, giving you resistance to martial attacks.",
  "Mushrooms begin to grow out of your head.",
  "You feel incredibly strong! You now have the strength of a Frost Giant (23 STR) for 1d4 hours.",
  "You can understand all languages for 1d4 hours.",
  "You cannot tell a lie for 1d4 days.",
  "You are able to pass through walls that are 1ft. thick, like a ghost.",
  "You suddenly forget the last language you spoke for 1d4 days.",
  "The ends of your fingers become very sticky. You can now climb walls for 1d4 hours.",
  "You are instantly teleported to the nearest body of water.",
  "You lose your reflection permanently.",
  "Your hair has the effect of being underwater permanently.",
  "You instantly become 1d6 years older",
  "You can speak with plants for 1d4 hours.",
  "Drinking this potion has allowed your consciousness to be noticed by a random deity! You have one chance to ask any yes or no question.",
  "All of your inner thoughts are audibly heard for 1d4 hours.",
  "Your pupils disappear! You are blinded for 1d4 hours.",
  "Your hair triples in length.",
  "You suddenly feel more drunk than you've ever been. You are gonna have a BAD hangover in the morning!",
  "You begin to grow insect mandibles on your face that last for 1d4 days.",
  "Wings sprout out of your back, allowing you to fly for 1d4 hours.",
  "Your eye color changes to a random color.",
  "You fall asleep for 1d4 days.",
  "You can smell gold from 50ft away for 1d4 days.",
  "You become transparent like a ghost for 1d6 hours.",
  "Your mouth vanishes for 1d4 hours. You are unable to speak.",
  "You can suddenly hear the thoughts of those around you in your head! You gain the effect of the Detect Thoughts spell.",
  "You turn invisible for 1d4 hours.",
  "Your size grows by 1d4 feet for 1d4 hours.",
  "Your skin color changes to a random color.",
  "You feel like you have springs in your feet! You can jump four times your normal jumping height for 1d4 hours.",
  "You grow a beautiful ginger beard down to your knees.",
  "Your hair color changes depending on your mood.",
  "Your AC increases by 1d4 for 1d4 hours.",
  "You create a clone of yourself every time you sneeze; each clone lasts for 1d4 minutes.",
  "You begin to vomit a swarm of angry insects. You can control them for 1d4 hours.",
  "You grow goat horns from the sides of your head.",
  "You begin to emit an odd musk from your skin, attracting wild animals to your location.",
  "You gain 1d12 temporary hit points.",
  "Your hands and feet grow webbing, allowing you to travel much faster in water.",
  "You gain a shiny film over your eyes. You can see in the dark for 1d4 hours.",
  "All the hair on your body falls off.",
  "You instantly become 1d6 years younger.",
  "You completely forget the last 24 hours.",
  "Your breath is now a light flurry of snow.",
  "For the next 1d4 hours, fire damage heals you instead of hurts you.",
  "Potion of Hecks: You can only use PG swear words for 1d4 hours. Oh, fork!",
  "Potion of Lying: You are incapable of telling the truth for 1d4 hours.",
  "Potion of Shocking Gasp: A chorus of voices gasps dramatically whenever you take an action for 1d4 hours.",
  "Potion of Portable Ram: Conjures a pocket-sized adult male sheep. He is adorable.",
  "Potion of Silence: Summons Specter Librarian who shushes anyone who speaks. Will attack anyone talking over a whisper after a few warnings. Librarian will not leave unless you sign up for a library card."
  ]
