module.exports = ["What are you running from?",
"Who do you blame most for your current troubles?",
"What secret do you most fear the team will discover?",
"Tell about your most embarrassing family member.",
"What is your latest addiction, and what have you had to sacrifice in order to get your fix?",
"What plan for your life do you just need your mother / father / grandparent to just let go of (and why won't they)?",
"Whose shadow are you desperate to get out from under? ",
"What \"family\" business did you leave behind, and what family member showed their disapproval most obviously?",
"Aside from never patching things up with your brother, what is your greatest regret in life?",
"Why do you feel you’ve missed out on the best life has to offer?",
"What happened that made you terrified of [wolves]?",
"What is the worst thing you have ever done to a loved one?",
"It is said that everyone has a price&mdash;how did you discover yours?",
"Why are you married if you aren’t in love?",
"Why won’t your family acknowledge your existence?",
"Who else knows you are a fraud?",
"How come you no longer allow yourself to have pets?",
"Why do you feel responsible for the loss of a loved one?",
"Who has hurt you most over the years and why do you deserve it?",
"What did you steal from your employer just before you were fired?",
"What is it about your love life that you fear your mother may discover?",
"With all this cash, how do you fend off boredom?",
"What feral animal almost killed you when you were a child, and how does this encounter still stay with you?",
"animal almost killed you when you were a child,",
"and how does this encounter still stay with you?",
"When you have trouble sleeping, what pleasant memory do you focus on?",
"Do you let the others know about that thrill you get from the adrenaline rush that accompanies combat? How does this rush affect how you fight?",
"What’s in your pockets?",
"What part of yourself do you find most embarrassing?",
"What do you think you are better at than you really are?",
"What can you do that most other people you know can't?",
"What is that thing, and why do you have it?",
"When friends describe you to a stranger, what one detail do they always include?",
"There is a heavy object in your backpack; what is it and what did you leave behind to make room for it?",
"How do you think the others treat you differently because you are the youngest in the group?",
"What drug are you now addicted to and why do you keep it a secret?",
"Why do you expect the others will look to you as the leader?",
"How did you get that scar?",
"What childhood hero has let you down?",
"What hobby do you have that surprises everyone?",
"What’s the worst way you could die?",
"What book have you read more than 20 times?",
"When do you feel most alone?",
"Why do you always wear that pendant, and what does it mean to you?",
"What part of your appearance would you most like to change?",
"What do you pretend to feel passionately about, just to impress people?",
"How did your parents die?",
"What made you laugh yesterday?",
"Who’s taking care of your two-year-old while you’re gone?",
"When the going gets tough, how do you respond?",
"What do you do to entertain guests?",
"Why are you uncomfortable around strangers?",
"What’s the most regrettable thing you’ve ever done due to being drunk?",
"What’s your sexiest feature?",
"What are you wearing that the others at first complained was too impractical?",
"How did your sister die?",
"What scared you most as a child?",
"What food that most people like can’t you stand?",
"You have a phobia you developed during your first [mission]. How has it interfered since then?",
"Even though the record was wiped clean, what haunts you from your past?",
"What soothes those tension headaches you get?",
"When do you feel most alone?",
"You have a somewhat shady past, leading to the acquisition of some very useful skills. What did you do, and what skill did you learn from it?",
"Where did you get that scar?",
"Why don’t you like being the age you are?",
"You are normally very close to your family, but recently you have fallen out of touch. Why?",
"When do you feel most alone?",
"Your training has given you a wide range of skills. What wasn’t covered?",
"What talent do most people never realize that you have?",
"What would you rather be doing for a living?",
"What are you most ashamed of?",
"Why is next month a big month for you?",
"Why were you thrown out of the military?",
"What did you hate learning as a child, but has since come in handy?",
"What unusual hobby do you have?",
"Your father pushed you to attain the sort of athletic glories he was not able to in his youth. What is your specialty?",
"What did your [older brothers] constantly tease you about when you were a child?",
"Like many [athletes], you’re fairly superstitious. What’s your good luck charm?",
"What could be considered your “signature” piece of jewelry?",
"What would ruin your reputation if anyone ever found out?",
"What embarrassing habit do you hide from everyone you know?",
"What one person do you actually care about that you have disappointed?",
"How badly were you injured in the last fight you were in?",
"What childhood nickname haunts you to this day?",
"What is the biggest crime that you’ve ever gotten away with?",
"What is your favorite item that, surprisingly enough, didn’t cost a lot of money?",
"What’s the worst thing you’ve ever done to a loved one?",
"What mannerism or speech pattern do you repeat often?",
"What personal possession are you never found without?",
"What have you been doing these past six months to make ends meet?",
"What irrational fear almost kept you from working as __________?",
"When was the closest you have come to death and how has that changed you?",
"You are never caught without your trusty what?",
"What part of your appearance are you particularly proud of?",
"Before landing your current job, what shady things did you do for money?",
"What is your biggest source of pride?",
"What personal affect do you always carry with you?",
"What are you uniquely talented at?",
"When are you at your calmest?",
"What do you consider more precious than your own life?",
"Most people who first meet you are surprised to hear about what line of work you are in. Why is that?",
"When you were a kid, what hobby did you have that bordered on obsession?",
"In your opinion what is your best feature? Do others agree?",
"What is your nickname and how did you get it?",
"Times are tough for everyone, but how have they especially been tough on you?",
"Which childhood memory do you have that often wakes you in cold sweats in the middle of the night?",
"What distinctive flair in personality or appearance are you known for?",
"When you are nervous or anxious, what do you tend to do?",
"What old hobby or interest are you known for all over town (that you wish people would just let go of)?",
"What warms your heart after a long day at work?",
"What restores your faith in humanity after a particularly frustrating interaction with some asshole?",
"Who, outside the team, thinks better of you than you do?",
"Whose disapproval actually gets under your skin?",
"Who are you running/hiding from, and why has Graywatch been a good place to hide?",
"What would you like your retirement to look like?",
"What motivates you? What drives you?",
"What sort of prophecy are you following (/ avoiding), and how do you feel about it?",
"What brought you here to Graywatch, and what are you sacrificing in order to stay here?",
"What is it about you that's made you hang on so long, despite -- well, you know...",
"What gives you courage?",
"What was your dream job? When and why did you give it up?",
"How did you gain your skills?",
"What do you do for fun?",
"Who was the first person you accidentally hurt with your powers/skills?",
"What is staying in Graywatch costing you? Why are you doing it anyway?",
"Why did [your mentor] agree to train you?",
"What accident or misfire taught you some humility or responsibility?",
"Who helped you realize you need other people?"]
