module.exports = [
  "Nearest sounded alarm goes off",
  "Grow trees right around caster",
  "Create much more water than intended",
  "Cone of silence",
  "Caster glows with faint aura",
  "Potion effects",
  "Hair changes color",
  "Turned into animal (can still talk) until after next rest",
  "Person you're trying to fool or impress gets to ask you one question that you must answer honestly",
  "Nearest tree comes alive and whacks you",
  "Change race (GM's randomizer)",
  "grow beard",
  "hair turns to feathers",
  "grow scales on torso (armor +1)",
  "eyes become segmented bug eyes",
  "stoneskin (armor +2)",
  "Body swap (switch character sheets)",
  "Instant rage: +5? temp hit points, +4 STR, +4 CON, advantage on fighting rolls, damage dice bumped up 1 size. Lasts one hour.",
  "Burning Hands. A thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must Defy Danger with +DEX. A creature takes 3d6 fire damage on a mixed success, or half as much damage on a miss. / The fire ignites any flammable objects in the area that are not being worn or carried.",
  "Cause Fear. Your own sense of mortality has been awakened; Defy Danger with +WIS. On a full success, you're able to shake off the sensation quickly. On a mixed success, roll with disadvantage on your next roll. On a miss, roll with disadvantage on your next five rolls.",
  "Compelled Duel. You are compelled into a duel; Defy Danger with +WIS. On a full success, you and one other creature in your immediate vicinity (GM chooses at random) are grumpy with one another for the next hour. On a mixed success, you each attack each other one time, then are able to shake yourselves out of it. On a miss, you continue dueling until something knocks you out of it. (After two 'rounds', you may both Defy Danger +WIS after your every strike, in hopes of ending the fight.) / The spell ends if a creature friendly to you damages your opponent or casts a harmful spell on it, if you end your turn more than 30 feet away from the target, or if another PC interferes in a sufficiently narratively interesting way.",
  "Comprehend Languages. For the rest of the day, you understand the literal meaning of any spoken language that you hear. You also understand any written language that you see, but you must be touching the surface on which the words are written. / This spell does not decode secret messages in a text or glyph, such as an arcane sigil, that is not part of a written language.",
  "Cure Wounds. You regain 1d6 hit points.",
  "Mass Cure Wounds. Every creature within 30 feet of you regains 1d6 hit points.",
  "Detect Aligment. For the rest of the day, you know the alignment (good, evil, lawful, chaotic) of all creatures within 30 feet of you. Similarly, you know if there is a place or object within 30 feet of you that has been magically consecrated or desecrated.",
  "Detect Magic. For the rest of the day, you sense the presence of unusual magic within 30 feet of you. You see a faint aura around any visible creature or object in the area that bears particular magic, and you may ask the GM one question about it from the Discern Realities list.",
  "Detect Poison and Disease. For the rest of the day, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you. You also identify the kind of poison, poisonous creature, or disease in each case.",
  "Disguise Self. Your whole appearance -– inc clothing, armor, weapons, and other belongings on your person –- looks immediately different. (GM will consult other players for ideas.) The change persists until you take damage or have a long rest.",
  "(You cannot change your body type, so you must adopt a form that has the same basic arrangement of limbs. Otherwise, the extent of the illusion is up to you. / The changes wrought by this spell fail to hold up to physical inspection. / To find out that you are disguised, a creature must successfully Discern Realities.)",
  "Dispel Magic. A spell or magic effect in your presence is ripped it apart. (GM chooses at random.)",
  "Earth Tremor. A tremor shakes the ground in a 10-foot radius. Each creature (including you) must Defy Danger +DEX. On a miss, take 1d6 bludgeoning damage and be knocked prone; on a mixed success, halve that damage. If the ground in that area is loose earth or stone, it becomes difficult terrain until cleared.",
  "Fog Cloud. You create a 20-foot-radius sphere of fog centered on your current position. The sphere spreads around corners, and the area is heavily obscured. Roll with disadvantage until you've moved out of the area or until a wind of moderate or greater speed (10+ mph) disperses it.",
  "Frostbite. Numbing frost forms on your extremities; Defy Danger with +CON. On a miss you take 1d6 cold damage, and roll with disadvantage for your next two attacks. On a partial success take half damage and roll with disadvantage for your next attack. On a 10+ roll with disadvantage for your next attack.",
  "Goodberry. Up to ten berries appear in your hand and are infused with magic. Eating a berry restores 1 hit point, and the berry provides enough nourishment to sustain a creature for one day. The berries lose their potency if they have not been consumed within 24 hours of the casting of this spell.",
  "Heroism. You are imbued with bravery. For the rest of the day, you roll with advantage in battle, and gain temporary hit points equal to your WIS modifier. After a long rest these hp disappear.",
  "Infestation. A cloud of mites, fleas, and other parasites appear momentarily on you; Defy Danger with +CON. On a miss take 1d6 poison damage and move 5 feet in a random direction. On a partial success halve the damage and move in a direction of your choice; on a full success, simply move out of the way as you choose.",
  "Jump. Your jump distance is tripled for the rest of the day.",
  "Magnify Gravity. The gravity in a 10-foot-radius sphere centered on your current position increases for a moment. Each creature in that sphere Defies Danger with +CON. On a miss, take 2d8 force damage and drop what you're carrying. On a partial save, half damage and drop one item. Roll +STR the next time you want to pick up any object not being worn or held (on a 10+, roll with advantage).",
  "Poison Spray. A puff of noxious gas erupts from your palm toward your face. Defy danger with +CON or take 1d12 poison damage.",
  "Primal Savagery. Primal magic causes your teeth or fingernails to sharpen, ready to deliver a corrosive attack. Roll with advantage to Hack and Slash against one creature within 5 feet of you. On a hit, the target takes 1d10 additional acid damage. After you make the attack, your teeth or fingernails return to normal.",
  "Shocking Grasp. Lightning springs to your hand and delivers a shock! GM will Hack and Slash at you on Yanoa's behalf (with advantage, if you're wearing metal armor). On a hit you take 1d8 lightning damage.",
  "Sleep. This spell sends creatures into a magical slumber. GM rolls 5d8 to total how many hp overall this spell can affect. Creatures within 20 feet of your current position are affected. / Starting with you and then moving to the creature that has the lowest current hp, each creature affected by this spell falls unconscious until either the spell ends, the sleeper takes damage, or someone shakes or slaps the sleeper awake. Subtract each creature’s hp from the total before moving on to the creature with the next lowest hp! A creature’s hp must be equal to or less than the remaining total for that creature to be affected.",
  "Speak with Animals. You gain the ability to comprehend and verbally communicate with beasts for the rest of the day. The knowledge and awareness of many beasts is limited by their intelligence, but at minimum beasts can give you information about nearby locations and monsters, including whatever they can perceive or have perceived within the past day. You may Parley with the beast even without Leverage.",
  "Sword Burst. A momentary circle of spectral blades sweeps around you. All other creatures within 5 feet of you must Defy Danger +DEX or take 1d6 force damage.",
  "Tasha's Hideous Laughter. You suddenly perceive everything as hilariously funny and fall into fits of laughter! You may Defy Danger +WIS; if the player laughs uproariously while doing so, roll with advantage. On a miss fall prone; you are incapacitated and unable to stand up. At the GM's discretion and whenever you take damage, Defy Danger +WIS again, until you succeed. If the roll is triggered by damage, roll with advantage (stacks with RP advantage). You continue laughing until you successfully Defy Danger +WIS.",
  "Thunderclap. A burst of thunderous sound erupts, which can be heard 100 feet away. You and each creature within 5 feet of you must roll Defy Danger +CON. On a miss, take 1d6 thunder damage.",
  "Zephyr Strike. For the rest of the day, you move impossibly fast, almost as if you're mounted on Greywind. Take advantage on ONE attack roll of your choice before the spell ends, dealing an extra 1d8 force damage on a hit.",
  "Speak with Dead. The next corpse you encounter will converse with you briefly (no time limit). It will answer any three questions you pose to it, to the best of the knowledge it had in life and the knowledge it gained in death.",
  "Gain Animal Companion. You develop a supernatural connection with a loyal animal. You can’t talk to it per se but it always acts as you wish it to. Name your animal companion and choose a species: wolf, cougar, bear, eagle, dog, hawk, cat, owl, pigeon, rat, mule. / Choose a base: A) Ferocity +2, Cunning +1, 1 Armor, Instinct +1. B) Ferocity +2, Cunning +2, 0 Armor, Instinct +1. C) Ferocity +1, Cunning +2, 1 Armor, Instinct +1. D) Ferocity +3, Cunning +1, 1 Armor, Instinct +2. / Choose as many strengths as its ferocity: Fast, burly, huge, calm, adaptable, quick reflexes, tireless, camouflage, ferocious, intimidating, keen senses, stealthy. / Choose as many additional trainings as its cunning: Hunt, search, scout, guard, fight monsters, perform, labor, travel. / Choose as many weaknesses as its instinct: Flighty, savage, slow, broken, frightening, forgetful, stubborn, lame.",
  "You are immune to being intoxicated by alcohol for the next 5d6 days.",
  "Your hair falls out but grows back within 24 hours.",
  "For the next minute, you must shout when you speak.",
  "Roll a d10. Your height changes by several inches equal to the roll. If the roll is odd, you shrink. If the roll is even, you grow.",
  "For the next minute, you regain 5 hit points at the start of each of your turns (10 actions).",
  "Each creature within 30 feet of you becomes invisible for the next minute. The invisibility ends on a creature when it attacks or casts a spell.",
  "Your skin turns a vibrant shade of blue. A Remove Curse spell can end this effect.",
  "An eye appears on your forehead for the next minute. During that time, you have an advantage on Wisdom (Perception) checks that rely on sight.",
  "You teleport up to 60 feet to an unoccupied space of your choice that you can see.",
  "You gain resistance to all damage for the next minute.",
  "You glow with bright light in a 30-foot radius for the next minute. Any creature that ends its turn within 5 feet of you is blinded until the end of its next turn.",
  "Illusory butterflies and flower petals flutter in the air within 10 feet of you for the next minute.",
  "Roll a d10. Your age changes by several years equal to the roll. If the roll is odd, you get younger (minimum 1 year old). If the roll is even, you get older.",
  "A Mirror Image of yourself appears next to you.",
  "You become invisible for the next minute. During that time, other creatures can’t hear you. The invisibility ends if you attack or cast a spell.",
  "You regain 2d10 hit points.",
  "You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have a vulnerability to all damage. If you drop to 0 hit points, your pot breaks, and your form reverts.",
  "If you die within the next minute, you immediately come back to life as if by the Reincarnate spell.",
  "You begin to levitate/fly.",
  "A Unicorn controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.",
  "You can’t speak for the next minute. Whenever you try, pink bubbles float out of your mouth.",
  "You are surrounded by faint, ethereal music for the next minute.",
  "For the next minute, your friends roll with advantage and your enemies with disadvantage.",
  "You teleport 25 ft. to the left of your location. A trail of fire appears from your starting position to your teleported position.",
  "The spell fails to take effect... until 1d4 rounds later.",
  "Something Fishy: You are left smelling of fish. The target of the spell also smells of fish. If the spell affects an area, the area smells of fish. If the spell produces a projectile the projectile becomes a fish.",
  "All the players randomly change bodies for 1d4 rounds.",
  "It rains literal cats and dogs for one round, causing 1d4 bludgeon damage to any creature hit by a dog and 1d6 slashing damage to any creature hit by a cat.",
  "Your hair follicles sprout feathers of one type, and in the next round these fall off or fly away; a round after, they sprout different feathers. This happens 1d6 times.",
  "A genie offers you a wish, but refuses to grant it and disappears.",
  "The caster and the target (or a random creature in range) both get an intense sense of kinship and refuse to fight each other for 1d4 rounds.",
  "You lose control of your bladder. Defy Danger +CON or or urinate on the spot.",
  "Your shadow detaches from you and becomes a Shadow (the creature, p262).",
  "You flash with golden light that seems to hang in the air around you. Everyone caught in this light (20 foot radius) receives double healing and cannot lie for the next 10 turns (one minute outside combat).",
  "You feel very attractive... All unsecured objects and creatures in a 100 ft radius moves towards you by 5 feet.",
  "You feel like you really need to sneeze. Defy Danger +WIS. On a miss, you sneeze, and involuntarily cast prismatic spray (https://www.aonprd.com/SpellDisplay.aspx?ItemName=prismatic%20spray) in the direction you are facing. On a successful save, you sneeze normally, without any ill effects.",
  "The world seems to slow to a crawl around you. You get to take 1 additional action.",
  "The smell of cinnamon fills the area in a 30-foot radius around you.",
  "A small songbird pops into existence in mid-flight 10 feet above you. Roll a d20. On a 1, the bird poops and it lands on you. On a 20, the bird poops and it lands on the target of your choice.",
  "A sinkhole, 20 feet deep and 10 feet in diameter, appears at a random location within 100 feet of you.",
  "You get the hiccups; they last for 1d6 minutes.",
  "Any non-magical pouches or containers on your person tear open and spill their contents onto the ground.",
  "Around you spawn 10 frogs; all of them are passive.",
  "Around you spawn 10 rats, all of them hostile.",
  "A lit birthday candle appears before you. In front of the candle is a note. The note reads “blow the candle out to make a wish.",
  "You grow an extra finger on one of your hands. A remove curse or remove debility spell can remove the finger.",
  "Your race changes every day for the next week.",
  "You know a new language, chosen by the GM.",
  "You experience extreme discomfort in their stomach for 1d4 turns before finally releasing a monstrous belch for another 1d4 turns. This belch functions per the description of the spell Gust of Wind, with the direction of the wind being whichever direction the caster is facing (https://www.aonprd.com/SpellDisplay.aspx?ItemName=Gust%20of%20Wind).",
  "For the next 24 hours, your nose grows outwards by 1 inch every time you knowingly tell a lie. The nose returns to its previous size once the duration is up.",
  "For the next hour, you burst into a fit of evil, maniacal laughter every time you open their mouth. Each time, roll Defy Danger +WIS or be compelled to pull a minor prank of some kind. The nature of the prank is at the player’s discretion, so long as it is suitably mischevious and harmless. If the player laughs so IRL, roll with advantage.",
  "Every writing in a 10-foot radius of you immediately transforms into incredibly petty criticism of you. If you read any of it, roll Defy Danger +WIS or believe whatever minor putdown the writing describes.",
  "A disgruntled 6-in pixie appears, flies up to you, punches you in the forehead, sprinkles you with a dust that makes you sneeze violently, and then vanishes in a puff of neon pink and orange glitter.",
  "Grow rabbit ears that give you advantage on all perception rolls for 1 hour.",
  "Your eyes glow and you're able to see in the dark, but the glow allows everything in the darkness to see you.",
  "You vomit up a huge slug after casting the spell.",
  "Your arms disappear and are replaced with mist-limbs. They can only lift up to ten pounds but can fit under doors, open non-magical locks, and even cool hot metals. Lasts for 1d10 minutes.",
  "You spit glitter when you talks. It gets everywhere. The effect ends after 1 minute but the glitter never goes away.",
  "The first person who says your name then has total mental control over you for 1d4 rounds.",
  "You turn into a marble figurine of yourself for 1d6 minutes.",
  "Any keratin on your body (hair, nails, feathers, some skin, horns, hooves, etc...) turns a vibrant hue.",
  "You are launched ten feet into the air and fall back down. Defy Danger +DEX or take 1d6 falling damage.",
  // "You turn into a massive oak tree.",
  "Your hair grows very rapidly (if male, this includes the beard). It grows to about 2meters length, and turns purple, green or blue.",
  "Bubbles sprout from your mouth every time you exale, for the next hour.",
  "Regardless of the amount of time that passes in game, you can see and hear all that happens in the real world surrounding your player for the next 1d6 minutes.",
  "Over the next 1d6 hours you grows 1d6 feet, but gain no mass, so a halfling would become an extremely tall thin creature. No negative effects, purely cosmetic, can be reversed with remove curse.",
  "Your eyes and veins glow in the dark for 1d6 days.",
  "A weapon within 30 feet of you becomes sentient; it's always grumbling about being dirty and grants disadvantage to the user if they don't spend an hour a day cleaning it.",
  "Your eyes flash with a strange color. To you, everybody's skin and muscles are transparent, revealing their organs. This lasts for 1 minute.",
  "The next piece of metal you touch turns to gold.",
  "All water in a 50 ft radius evaporates instantly.",
  "A small lead figure of you in the exact pose they were in appears in midair and falls to the ground. Despite being so small, it weighs exactly as much as you.",
  "Your hair disappears, reappearing 1d6 days later, washed, braided, and decorated with flowers.",
  "Instead of the intended effect, 10d10 trees in the area grow mouths, and begin singing for 1d8 rounds. The song is a soothing one, distracting all who can hear it into just waiting and listening.",
  "You are trapped in a giant glass ball. Must be broken to be freed.",
  "A burst of glitter explodes around you. It does no damage, but you will be picking glitter off your skin and belongings for the next 1d8 months."
  ]
