module.exports = [
  "Invisible Ring: When activated, the ring turns invisible.",
  "Wand of Night Vision: It's just a basic torch.",
  "Rope of Entanglement: A rope that cannot be untangled.",
  "Elixir of Confusion: Just a vial of very cheap booze.",
  "Wish Scroll: When activated, this scroll summons the closest wishing well to the player's location.",
  "Amulet of Spell Storing: Stores one spell cast into it. Never lets it out.",
  "Alchemist's Jar: A glass bottle once owned by an alchemist.",
  "Skeleton Key: A key made from a skeleton's femur bone. It doesn't unlock anything.",
  "Hearth Potion: Deals 1d4 fire damage when consumed.",
  // "Ring Of Attunement: While worn, this ring grants the user an extra attunement slot. Requires attunement.",
  "Wand of Disintegration: The wand turns into dust when used.",
  "Glasses of Perception: A normal pair of reading glasses.",
  "Sword of Sunlight: A sword that shines as bright as the sun when unsheathed, blinding all creatures within line of sight, including the wielder.",
  "Boots of Teleportation: Clicking the heels together teleports the boots, but not the wearer, to the destination.",
  "Sword of Judgment: Allows wielder to locate the nearest certified judge.",
  "Ring of Regeneration: This steel ring will slowly repair itself over the course of 1d4-1 days if broken. It provides no other magical benefits.",
  "The Infinite Gold Pouch: A gold pouch that produces an additional illusory gold for every gold pulled from it. A DC 15 perception check dispels the illusory gold pieces.",
  "Ring of Detect Fire: A ring that helps you detect if something is one fire. Range: touch.",
  "Wand of Amazing Pigmentation: An ordinary paint brush.",
  "Potion of Hydration: A glass vial filled with water.",
  "Wand of Secrets: The purpose and how to use this wand is a secret. No one knows what it does.",
  "Scroll of Fire Detection: If the area around the scroll is on fire, then the scroll will warn you. By burning. Because it's paper.",
  "Fingerless Gloves: The gloves make your fingers invisible.",
  "The Orb of Slope Detection: It rolls down any slope present. Magically, of course.",
  "The Weather Globe: This snow globe features a snowman holding an umbrella. The little sparkles in the globe dance around on their own whenever precipitation of any kind is going on.",
  "Little Steve: This tiny doll has a small hole in its mouth. When you press your finger into its back it makes an over exaggerated 'Bleh' sound and spits a tiny handful of confetti about three inches.",
  "Decanter of Endless Water: Decanter included, endless water sold separately.",
  "Wand of Wonder: Everyone who sees the wand for the first time must say 'wow, neat!' or something to that effect.",
  "Shield +1: A regular shield with '+1' as the emblem.",
  "Wand of Create Wand: When used, creates a new Wand of Create Wand, previous wand disintegrates.",
  "Invisibility Cloak: The cloak is invisible.",
  "Movable Rod: This small rod, that fits in a satchel, is easily moved from place to place.",
  "Cloak of Disease Immunity: The cloak cannot be infected by any diseases.",
  "Flame Resistant Shirt: When you put it on, it becomes soaking wet.",
  "Heavy Flail: A normal flail that makes the wielder 50lbs heavier.",
  "Fire Arrow: Any creature hit is immediately and inextricably fired from any employment they have.",
  "Boots of Extra Action: You gain an Action by tapping the heels together... but it takes an Action to do so.",
  "Tome of Uselessness: Whenever this plain brown tome is opened, it closes (as the open/close spell).",
  "Pet Rock: At first look, this seems to be a completely normal pebble. And it is. That merchant just put an aura on it to make you think it was magical.",
  "Belt of Self-Disguise: This belt can be used 3 times per day to use Disguise Self as the spell. However, you may only disguise yourself as yourself and the spell gives no bonus to Disguise checks.",
  "The Lucky Charm: This charm is very lucky. Unfortunately, none of its luck seems to brush off on its owner.",
  "Solar Torch: This magical torch is devoid of heat but will stay lit as long as it's in bright sunlight.",
  "Bead of Usability: When activated, the Bead of Usability is used. One use.",
  "Ring of Non-visibility: You become invisible, as long as no one is looking at you.",
  "Hat of Disguise Self: Once per day, on command, this hat will cast Disguise Self. On itself.",
  "Two-Handed Sword: Has two nonfunctional hands built into the hilt.",
  "Ring of Invulnerability: The ring can never be destroyed.",
  "Rod of Wonder: When activated, makes a random 'I wonder' statement.",
  "Wand of Cold: Ranged touch attack, gives the target a cold.",
  "Feather of Ring Falling: Anyone holding this feather has their rings fall off.",
  "Rod of Wander: A rod that causes the owner to have no sense of direction.",
  "Potable Hole: A hole that is not portable, but is full of water that is safe to drink.",
  "Spell Scroll: When used, a voice calls out 'S-C-R-O-L-L'.",
  "Potion of Fire Breath: Just an extremely spicy hot sauce.",
  "Boots of Levitation: The boots float 1 foot off the ground... but only when not worn by the player.",
  "Amulet of Detect Magic: When the wearer concentrates on this amulet, it will magically detect the closest magical item: itself...",
  "Crystal Ball: This is just a ball of glass that looks kind of cool, if detect magic is cast it is seen to not contain any arcane properties.",
  "Boots of Evasion: These arcane boots will use whatever means necessary to evade the user's attempts to put them on. If equipped, the boots of evasion will run to the nearest large fall, and attempt to kill the user.",
  "Ring of Vampirism: This ring will curse the user with the insatiable desire to drink blood. This blood does not benefit them at all and the user will most likely develop hemochromatosis and their health will suffer.",
  "Ring of Water Breathing: This ring allows the user to breathe underwater by altering their body to have gills. Unbeknownst to the user, this comes at a savage price. Upon the third use of the item, the user is cursed to have gills permanently, and loses their ability to breathe air, making water an essential for oxygen intake.",
  "Vial Of Holy Water: This water is said to be blessed by the gods. It's not however, it's just water, slightly muddy at that.",
  "Mage's Hand: This is quite literally the hand of a deceased Mage. Upon inspection, it is unclear how it was unobtained or if it was willingly.",
  "Miniature Piggy 'Bank' Companion: This miniature pig is the perfect companion for an adventurer with a need for a place to store their gold. Upon being fed gold coins, the miniature pig swallows them for 'storage.' In actuality, the coins are quickly broken down and digested by the pig, unbeknownst to the owner. When the owner does finally go to remove gold from the pig, they discover there is no gold to be found.",
  "Boots of Fleeing: These Boots have tiny little wings. When an attempt is made to wear them, they flee.",
  "The Bag of Bags: a bag of holding that may only hold purses, rucksacks and the like.",
  "Potion of Bravery: It's just a regular vial filled with ale.",
  "Disc of Bemusement: An apple-sized brass plate studded with buttons, gears, levers, switches, and other doodads, sold as a time-killer. The user believes they've been playing with the item much longer than they really did - a minute of fiddling could feel like hours.",
  "Ring of Primal Rage: Upon donning the ring, the user and everything on their person, including the item itself, transforms into a dire predatory creature. Over a period of hours, they lose their sentience and begin devolving - a dire wolf could turn into a regular wolf, then a saber-toothed rat, then a primitive amphibian, then a tadpole. Upon devolving into a single-celled organism, the user instantly reverts to normal in the nearest open space, extremely tired, thirsty, and with 2D6 hit points remaining.",
  "Oil of the Ghost Thief: When the entire jar of greasy ointment is rubbed into the skin, this pungent concoction renders the user's naked body, and anything in their hands, imperceptible to all natural senses. The oil gradually rubs off over 1D4 hours, and the instant the effect ends, all witnesses immediately recall the stinky, naked, presumably larcenous user as if the oil was never applied.",
  "Hardwick's Handy Hairbrush: This handsome grooming tool is sculpted from aromatic wood, inlaid with glistening fire opals, and studded with supple boar bristles. With a thought, the brush instantly appears in the user's hand. The merchant has sold the same brush to dozens of chumps, using its ability to remotely swipe it from the previous buyer.",
  "The Vaporblade: This scabbard holds a handle, but no blade. The seller claims its immaterial edge manifests upon throwing a slash, and demonstrates by effortlessly cutting a sheet of parchment, a bundle of sticks, etc. In reality, there is no blade - the handle bears a curse that rends nearby wooden objects.",
  "Holy Vault of the Crusaders: Precious metals and gemstones locked in this cold-iron strongbox vanish from the material plane. If the box's owner unlocks it while reciting a brief prayer, all of the stored objects will reappear, spilling out if necessary. The items aren't held in a holy plane like the seller claimed - they're actually sent to a gigantic Bag of Holding in his basement. After 1D4 weeks, or once the total exceeds 1D10 * 1000 GP, the seller will steal everything stored in the boxes and skip town.",
  "The Lute of Destiny - Notes strummed on this black-enameled instrument, strung with muscle fibers from a demon's right arm, are uncannily loud and mildly distorted. When held, musical inspiration floods the user's mind, and when played, a crowd inevitably forms. In reality, the 'inspired' songs are incoherent and obnoxious, and the crowd is an illusion visible only to the player.",
  "Pulsipher's Pocket Privy: A porcelain model of an outhouse, about the size of one's palm. When the door is opened, a simple wooden outhouse pops into existence in a nearby clearing. 'Waste' dumped into the cistern vanishes from the material plane. After 2D6 days, or when the model is shattered, the magic fades and the outhouse permanently reappears... along with the accumulated 'waste.'",
  "Miska's Tonic: When dabbed between the eyes, this glowing fluid provides a small buff to Intelligence, the ability to read and memorize information twice as fast, and a sense of mental clarity that lasts for about two hours. Unfortunately, it's also a powerful pheromone to Mind Flayers, who can psychically sense it from hundreds of miles away... and repeat application strengthens and prolongs the effect.",
  "The Money Machine: Insert a coin into this clattering, steaming contraption, and a minute or so later, two pop out. To the party's surprise, it's the real deal; the seller claims they need a lot of money ASAP to make good on a bet. What they don't tell you is that they stole it from the local mob, and their toughest kneecappers are hot on your tail.",
  "Potion of Love: It makes you fall in love... With the potion. It just tastes REALLY good.",
  "A Flying Broom: The broom can only fly when no-one is holding it making it impossible for someone to ride it.",
  "A Magic Spoon: Anything eaten from this spoon has the effect of remove poison. However, any food eaten with this spoon always tastes awful.",
  "A Pearl of Spell Storing: This pearl can store a 1st level spell only. Once the spell is casted from the pearl, it targets a creature at random (PC included).",
  "Book for Dummies: A book designed to learn the basics of a subject. Upon finishing it, the target can add +5 to the next roll made with disadvantage. However, all other rolls made within the next minute will also have disadvantage. Once read, it cannot be used again for this purpose.",
  "Wand of Wonder: When used, everyone in a 10ft radius may let out a Wow in perfect unison. The individual inflections may still be able to be interpreted as genuine or sarcastic and are not forced by the wand.",
  "Marble of Emotion: Pitched as a marble that changes color depending on the interlocutor's mood, but in fact it just changes color in a random pattern.",
  "Stair of Extending: A magical stair that can be comfortably carried on someone's back and can extend up to 50ft. The only snag is that it's really a mimic that each night ( quiet time ) tries to go back to its owner and feeder - the vendor.",
  "Wand of Snowballs: Creates a snowball in thin air and launches it at a foe. Unusable in good weather. The worse the snowfall at time of casting, the bigger the snowball.",
  "Disappearing Ink Vial: In 1d6 days, the bottle or vial disappears, leaving the ink to make a mess.",
  "Rope of Untying: A rope whose knots always come loose at a slight tug.",
  "Goggles of Mind Reading: When you wear these goggles, the world around you can hear your thoughts.",
  "Boots of Feline Agility: Wearing these boots gives the wearer advantage on stealth checks. However, whenever the wearer is surprised, they immediately jump their full movement in a random direction (roll 1d4/1d8 to choose direction).",
  "Staff of Sleep: Any creature can be put to sleep with this piece of wood if you hit them hard enough with it.",
  "Silent But Deadly Alarm: This small marble will send a silent message to the owner every time a creature gets within 10' of the marble. The message is in the form of an invisible cloud of stench. Others can smell it but don't know what it means.",
  "Scammer's Coin: Any change given to the players from the scam artist has at least one tracking coin in it. If the players have been quite profitable and seem easy to dupe then all the change also returns to the scammer after 1d4 days.",
  "Ring of Drowning Immunity: A full sized orange life ring. You cannot submerge whilst wearing it.",
  "Lesser Scroll of Summoning, Rabbit of Caerbannog: Summons a normal white rabbit.",
  "The Orb of Slope Detection: This orb rolls down any slope present. Magically, of course.",
  "The Weather Globe: This snow globe features a snowman holding an umbrella. The little sparkles in the globe dance around on their own whenever precipitation of any kind is going on.",
  "Wand of Create Wand: When used, this wand creates a new Wand of Create Wand, and the previous wand disintegrates.",
  "The Mightiest Sword: An elvish looking blade with intricate feathery looking designs on it. When its command word is spoken it is said to become mightier than any sword. (It turns into a giant quill/pen.)",
  "Movable Rod: This small rod, that fits in a satchel, is easily moved from place to place.",
  "Amulet of Luck: An extremely lucky amulet that never comes to any harm. This effect doesn’t affect the user at all.",
]
