module.exports = [
  "Mordenkainen's Magnificent Malt: A beer with just a lower alcohol percentage, for the adventurer that expects he needs to be sober for the upcoming nights.",
  "Mordenkainen's Malificent Malt: A beer with an alcohol percentage similar to that of whiskey that has its own plans for naive adventurers.",
  "Elven Absinthe: With an herbal taste, one can easily see why it is a popular drink among the elves. Drinkers take care, though, as it is much more potent than it seems.",
  "Underdark Ale: It isn’t really from the Underdark, but the brewers figured the name would be eye-catching (they weren’t wrong). It is a dark, potent Burton ale found in pretty much every tavern.",
  "Goodberry Sangria: Delicious, nutritious, and pricey, this sweet concoction is a fan favorite.",
  "Devil's Blood Whiskey : Nobody knows whether there truly is devils' blood in this aged whiskey or not... but the feeling of fire in the chest definitely seems to support the claim.",
  "Gore: Fermented pigs blood and cane sugar.",
  "Iced Lager: From enchanted casks. Tastes as cool as the northlands.",
  "Draconic Ale: A strong but rather basic ale; there are 10 additional varieties of it based on the chromatic and metallic dragons.",
  "Red Draconic Ale: Infused with cinnamon; feel the burn.",
  "Blue Draconic Ale: Infused with prickly pear cactus; causes slight static charge when drank.",
  "Green Draconic Ale: It feels like you're drinking straight poison, this ale is so strong.",
  "Black Draconic Ale: Infused with various citrus to give it a slight acidity.",
  "White Draconic Ale: Magically enchanted to stay close to the freezing temperature of water. You can feel it go all the way down.",
  "Copper Draconic Ale: Infused with ginger; causes you to hiccup a few times.",
  "Bronze Draconic Ale: Infused with coconut and pineapple. Smells like the sea.",
  "Brass Draconic Ale: Infused with agave; makes you slightly sleepy.",
  "Silver Draconic Ale: More of a cider than an ale, it is magically enchanted to be the perfect temperature for the drinker. It is made using the finest apples.",
  "Gold Draconic Ale: Infused with cinnamon, little gold flakes can be seen floating within. Causes the drinker to belch small harmless flames for the next 5 minutes.",
  "Patrons Pint: A drink that shifts its type to correspond to the drinkers chosen patron/deity/inspiration. Dark ale with foam in the pattern of tentacles for a Great Old One, pale ale with an evershifting cloud for Archfey, and spiced mead with a bubbling fire at the base for the Fiend patron.",
  "Cave Breath Hard Whiskey: Of gnomish make. Gnomes don't do much alcohol, so when they do, you know they'll apply the same wacky engineering to make a bottle of essentially 50% rubbing alcohol and 50% gasoline that will 100% get you effed up.",
  "Bubblegut Ale: A dark, heavy brew with hints of clover. I bet you can't drink a pint without burping.",
  "Frost Giant's Kiss: A chilled shot that leaves your breath frosty for 12 hours.",
  "Red Fez: A heady palm wine brewed in the desert regions.",
  "Tectlate: An ancient fermented corn drink. Based on a thousand year old recipe.",
  "Miguelabu: It's a drink that is based off of Malibu but with an aasimar's twist.",
  "Awakened Wine: A vineyard owned by a druid who cast Awaken on his vines. Claims it creates better wine when working with the plants input.",
  "Spore Wine: A svirfneblin wine made from crushed mushroom. Despite being considered top shelf due to its difficultly to obtain, most surface dwellers find it stomach turning. Definitely an acquired taste.",
  "Pixie Cider: Served by the teaspoon, this surprisingly potent drink leaves the drinker seeing stars and 'pixie dust' trails behind all other creatures for 1d4 hours.",
  "Vegan Blood Wine: Wine that has been magically flavoured to taste like blood, for the socially conscious vampire.",
  "Zombie Whiskey: An out-of-touch elf decided the undead were 'in vogue' this season and created this whiskey from grains soaked in rotting carcasses. Tastes absolutely awful but somehow leaves the drinker without a hangover.",
  "Jungle Juice: A spirit from Chult, made from berries grown wild in the jungles.",
  "Ver-poo-th: A derogatory name for a vermouth from the moonshae isles that is made from cherries that have been eaten and defecated by a native tree cat.",
  "Orcish Rotgut: A surprisingly pleasant tasting, blood red alcoholic beverage, with secret ingredients that hide the fact that it's incredibly potent. Those particular ingredients do not sit well with non-orcish guts. Anyone drinking it that is not an orc or half-orc must make a DC 15 Constitution saving throw a half hour after drinking it (separate from any checks that might be made to resist intoxication). Failure means the drinker feels painful nausea for the following 12 hours, during which the drinker cannot benefit from short or long rests and suffers disadvantage on attack rolls, saving throws, and ability checks.",
  "Korin's Dragonmint Mead: A delightfully light and crisp drinking mead that has a hint of herbal flavors and a tiny finish of mint. Tastes awful to paladins for some unknown reason.",
  "Kobold Kombucha: Comes in all the chromatic flavours, perfect for your hippie-dippie druids and teetotaler paladins.",
  "Rubyrump's Red Ale: Made with all the care and love you'd expect from a dwarf with the name Rubyrump. A warm inviting red ale with a smooth finish. A winking dwarf caricature with a foamy flagon and 'It'll put that ruby twinkle in yer eye' written in bold yellow letter on the barrels, crates, bottles, limited edition flagons, etc.",
  "Jotenhiem's Ringlefich Brandy: Suprise suprise. Who would have guessed some of the best brandy in the region comes from some very outlander-ish Dragonborn living in the mountains. A favorite and well kept secret amongst the locals of the area. Best served warmed and paired with aged goats cheese.",
  "Denurs Golden Ale: A light beer with moderate hoppy finish and a crisp mouthfeel with the smallest notes of hickory and rasberry. Simple enough to be enjoyed casually, but with just enough hidden suprises for a beer lover to find interesting.",
  // "Gerlach's Winery: A merlot grown by gnomes. They say the process with which they make this particular merlot is actually a secret formula locked away in a vault guarded by two ogres too dumb to read but too smart to turn down the gold the Gerlach family puts up for their services.",
  "Gentleman Jim's: The mass produced whiskey that comes from the city in large shipments. Straightfoward and simple, cheap but effective for livening up a party. The black bottle with flourishes on its print is easily recognized by whiskey savant and dullard alike.",
  "Shanty Shandy: Allows the drinker to 'see' musical tunes hanging in the air. Taking a swig before dancing dramatically improves one's skills. Powerfully addictive to bards, as it connects them with music on an intimate level. Bards who imbibe will soon be unable to play without it.",
  "Goblin Gutrot: Brewed in a local cave by the smartest of goblins, this stuff is your one copper for two flaggons. It will destroy your liver, tastes like shit and may have negative impact on you from cave rot. But at 2 tankads minimum per copper, sometimes you just want to get drunk.",
  "Brandis' Brandy: Named after a famous pirate captain, this brandy is cut with seawater, and the barrels it is aged in are submerged in the sea for a year before it is served to the patrons.",
  "Stahn Brown Ale: A rich dwarven-brewed ale, dark in colour and very strong in flavour. Regular consumption results in an inability to feel the cold, refusal to wear a coat even when snowing, and an immense craving for finely sliced spiced lamb with salad on a flatbread.",
  "Rats Piss: Served in goblin bars exclusively, in a stitched-up ratskin. Extremely powerful drink. It is customary at goblin parties to 'drain the rat' by squeezing the skin dry in one go, similar to doing a yardie at a 21st.",
  "Moody Cider: Made from the apples of treants. However they were feeling when the fruit was harvested is the emotion that the drinker will experience for the next hour. Every drink is a gamble! Exuberance, depression, fits of laughter, shyness, love, or confusion.",
  "Ooze Bane: A brutally strong and rough spirit that doubles as a solvent for oozes and jellies!",
  "Choke Ale: A nearly undrinkable goblin beverage made from fermented garlic. It is traditionally served with chunks of garlic floating in the glass, hence the name.",
  "Gru'sh: Made of the bladders of large sea-life, this coastal inn sells this oily black beverage in large serving sizes. It is extremely potent, and had it not been for its fluidity, it would be extremely hard to keep down. If spilled, you must make a Dexterity DC10 Saving Throw to not slip on the tile it was dropped on or fall prone.",
  "Dwarven Tomb: Also called a Pondahl Tafone by elitists who don't want to sound like a ruffian when they order it, this drink is a dwarven-made black mead. Besides its blackcurrants, it has a very earthy flavor and a grit to it. While someone who calls it a Pondhal Tafone would likely explain to you in depth that the earthy flavor and grittiness comes from a complicated and sophisticated fermenting process involving fresh roots that only a trained pallette can detect, the validity of this claim could be brought into question as the beverage is traditionally served in an unhewn stone cup. Something which those who call it a Dwarven Tomb, spare no time in pointing out, much to the frustration of their well dressed counterparts who are often mid-explanation.",
  "Dark Smoke Bourbon: The best bourbon can only be appreciated with a fine cigar. That's why every bottle has a box included.",
  "Party Poppers: A magic cider that has a prize appear after it is drunk. It's bottle cap also has numbers that act like a lottery.",
  "Black: A thin translucent black liquid that tastes somewhere between salt water and acrid smoke. Burns going down, ignites at the faintest rumour of a flame, but it's cheap as it comes (2cp for a bottle big enough to knock out an average human).",
  "Brown: Looks like thick opaque brown ale with a lighter brown foam head. There is a noticeable delay when pouring and it will develop a skin if it sits out for too long. Tastes like strobg, creamy, slightly-acidic ale, but fill you up like a good lunch. Often described as a 'Meal in a Mug'.",
  "Lathander's Light Ale: A pale ale brewed by the clerics at a temple of Lathander. Rumoured to grant minor boons to followers of Lathander, which the temple will neither confirm nor deny.",
  "Borovian Wine: A rich blood red in colour, the bartender doesn't remember ordering it, but found it in the cellar so figured he might as well sell it. Not suspicious at all.",
  "Beholders Tears: A clear spirit that causes very vivid dreams the next time the drinker sleeps. Actually just made from a plant know for it's hallucinatory effects but that doesn't make for an exciting name.",
  "The Princess: A reddish spirit with a fruity taste. Because of the sweetness, the colour and that is sometimes served with some flower inside the glass, some people may think of it as weak, but is extremely potent and usually a few glasses are enough to wake up the morning after with no recollection of what happened.",
  "Dragonblood: A dark red wine with an addition of some spice. It's called Dragonblood becouse of the colour, the fact that is served warm, and it's very spicy.",
  "Fairy Gift: A liquor with an herbal flavour and a distinct light-blue colour. The colour is given by some rare plant and can remain for some time on your tongue or your lips",
  "Holy Springs Golden Ale: Claims to be made from water drawn from a sacred stream and then blessed by a prophet of the gods. Everyone knows it's all bullshit but drink it anyway because it's super tasty.",
  "Nilbrew: A noxious brown liquid that is legendary for its terribleness and high alcohol content. People ritualistically drink this foul brew calling the process 'taking the wanderers journey' due to the tendency of these impromptu acolytes to end up in the most unusual places.",
  "Druidic Sangria: Messes with your visual color spectrum",
  "The Walking Red: A unassuming dry red wine that the players are instructed to 'let breathe,' for a while before consumption. The longer the player lets it sit, the more it seems to actually be breathing. If left long enough, it will crawl out of the mug and wander away.",
  "Elven Ale: Made with a recipe stolen from a dwarven brewery. It's drinkable, but not great.",
  "Dwarven Wine: Made with a recipe stolen from and elven winery in retaliation to them stealing a beer recipe. Slightly more successful than the elvish attempt at beer, but not by much.",
  "Belbuck: A transulent green, spearmint beer favored by halflings.",
  "Blue Eyes Wine: A halfling wine made from blue grapes.",
  "Luiren's Best: A black-as-ink, very sweet stout. Brewed by a coastal clan of Luiren, Smokardin.",
  "Pulsch Brown Ale: Halflings make this. It has a pleasant, nutty flavor.",
  "Moon Mountain Ale: Very popular drink from the Moon Mountain Brewery in the Forgotten Realms.",
  "Stonesulder Wine: This yellow-hued, sharp-flavored liquid is made by the sap from demon plants from the Abyss, which is then fermented in wooden barrels.",
  "Aelfengrape Wine: This elven drink is extraordinarily potent but doesn't have a refined taste.",
  "Elven Aleeian Wine: Grapes plucked from wild vines deep in the forest. Takes several months to create one batch.",
  "Dwarven Garnet Wine: Made from grapes high in the mountains.",
  "Dragonbite Bitter: Exceptionally dark beer. Recipe is centuries old, only the Dragonbite Brewery makes it.",
  "Dwarfhead Stout: A powerful, 'day to day' brew favored by warriors. Mostly found in dwarven communities.",
  "Frenzywater: Extremely potent. Bottle may sometimes spontaneously burst into flame if left in sunlight. Might cause a berserker rage.",
  "Gnome Golden Light: A lightweight beer with flowery accents.",
  "Elven Mead: Elves use exotic honey in the forest to make this. Even dwarves like this drink.",
  "Elven Moondrop: Exquisite drink made by experts using fresh dew and moonlight.",
  "Moonslake: Minty halfling drink. Alcoholic apple cider that's been mixed with water in which crushed mint has been boiled, then strained out again. Cool taste, humans don't like the after-taste.",
  "Darklake Stout: This drink is a signature ale brewed by the Muzgardt clan of Duergar that live in the Underdark settlement of Gracklstugh in the Forgotten Realms.",
  "Tea: It's just a nice warm cup of tea. Perfect after a day on the town, or a day killing monsters. Have it black, or with sugar and milk if you prefer.",
  "Coffee: For those nights where you need to stay awake on guard duty.",
  "Three-Ashes Tea: This beverage is a cold, bitter tea, said to aid in meditation. Popular with the Dustmen in Sigil.",
  "Firewine: Brewed from the Arborean fireseed, firewine is a strong, smoky-flavored wine. It is often consumed alongside fireseeds, as each enhances the flavors of the other when consumed together.",
  "Oathbeer: Dwarves drink this as part of a ceremony to seal a pact, or as a sign of friendship and devotion. All involved swear an oath before a priest, shed blood into the beer, and the cup passed around. Oathbeer binds the drinkers to the oath, as long as they partake of their own free will. Violating the pact brings a curse upon the oathbreaker.",
  "Dwarven Grave Ale: When a great dwarven hero dies, skilled brewmasters are commissioned to create a signature ale to commemorate his passing. It is stored in barrels that have carvings of scenes of the dwarf's great deeds.",
  "Golden Maggot: A terrible name for a surprisingly fruity pale ale. The recipe is a close-guarded secret.",
  "Island Kava: A dull beige beverage made from a plant root from distant lands. A pungent earthy taste. Will make your lips numb and your brain number.",
  "Jacka's Salted Mead: Tastes like honey-cured bacon. Looks like foul pond scum.",
  "C'Suk's Fortified Fruit Wine: The label literally says 'Will get you pished'",
  "Owlbear Brew: Cheap and disappointingly watery lager. Inexplicably, the label depicts an Owlbear with massive breasts.",
  "Owlbear Premium Brew: A palatable lager that won't break the bank. The label depicts an Owlbear with unfathomably large breasts and a paper party hat.",
  "Human Cider: Made with apples, not humans. Touts itself as a 'genuine human recipe' and has a picture of a happy farm girl on the label. Pairs well with belly pork.",
  "Wyvern 981: A viscous liquor with an indescribable taste. Some have likened it to being punched in the nose with an onion whilst a fond memory kissed you gently inside your throat.",
  "Gelatinous Gin: One curious and profitably end point in the wizardly experimentation of Curzan is this breed of gelatinous cube, bottled, intoxicating and relatively safe for consumption. This lively cousin of the Gelatinous Cube dances wildly in its bottle when it is given a little shake, as if it is sloshed itself. Sometimes brewers add flecks of precious metals like gold simply for visual effect and conspicuous extravagance. Typically served in a shot glass, the gelatinous drink goes down with a slightly paralyzing effect giving the drinker a signature raspy lisp. It is sweet from the molasses half-metabolized into alcohol (yes, it's technically a rum) and flavored by other organic material added in the brewing process—berries are popular, but some adventurous combinations include ghost peppers, whole octopi and cilantro. Left too long on its own, it has been known to sneak out of the glass and crawl off a bar.",
  "Infernal Absinthe: Dangerous stuff. Functionally a deal with a devil in a bottle, infernal absinthe can produce visions in some, nightmares for others. Most people just pass out. If you drink enough of it, you might be in for a terrifying result.",
  "The Flaming Dragon - A spicy beer that causes the user to breathe fire when they burp.",
"The Banshee's Breath - white, swirling liquor made from a special translucent wild berry. Tastes sweet, has an effect similar to mint gum in that it always feels cold.",
"The Mountain's Bounty - A fine liquor made using water from a glacial stream. Always refreshing, and always makes you feel cold no mater the weather.",
"Mawxie - A drink all the locals cite as a local treasure. Tastes disgusting.",
"Bog Grog - A mix of Rum, Orange Juice and fermented herbs that, when drunk, causes the user to gain advantage on saving throws against being poisoned for 30 minutes.",
"Frost Mead - Honey and the tear of an Ice Giant make this shot. The crackling blue sparkle and the jet of icy breath you have for rest of the day is worth the expense.",
"Weatherbee’s Whirler - Invented by the perhaps too inventive Filbus Weatherbee, this drink is testimony as to why it is a bad idea to point a gnome’s sharp mind towards the creation of a new brew. After spending many years living among the dwarves, Weatherbee made his way home with a drink even the stout folk couldn’t handle. This monstrosity is laced with latent magic designed to lessen the chance of drinkers dying from its ungodly alcohol content, and reportedly tastes like “A kick in the face from a horse.” After one shot of this drink, the drinker is shunted into a chaotic haze of blurry awareness, bolstered confidence, and overpowering drunkenness. In addition, the latent magic in the brew causes minor, uncontrolled magical effects to occur around the drinker at random times during the haze. The nature of these effects is up to either the DM or the player, so long as the effects are sufficiently insignificant. After 1d4 hours, the haze drops away and the drinker immediately and almost violently falls into a deep sleep so that they may recover.",
"Dragonborn Bloodwine - When you drink it, you are able to use a breath attack once within the next 10 minutes.",
"The Quieker - nasty rum that gives a high pitched voice for 1d4 hours.",
"Faerie Fireball - a delicious cinnamon whiskey made with a touch of Fey magic. Causes uncontrollable hiccups for 1d4 hours. With each hiccup a small cloud of shimmering breath is released.",
"Lily in a Well - a tall mug of ale, half full with an edible flower garnish.",
"Hammer Beer - One glass will make you feel like you just hit yourself with a hammer. Minus 5 HP.",
"Dragon's Piss - A beer that tastes exactly like one would suspect by its name. For sure not a drink you need a second one of.",
"Shamrock Shake - Instant dc15 con save. On fail the patron is incapacitated. No save required if patron has Irish (sounding) accent.",
"The Sun's Glory - A citrusy cider that makes your eyes glow like an Aasimar.",
"Black Midnight - A drink created by necromancers to honor fallen necromancers, Bitter with a touch of rum. Those who drink it have nightmares of dying and spending an eternity rotting away inside a coffin. This helps enforce necromancers to contemplate their own moralities.",
"The Phoenix - A peppery drink that burns on the way down, and then again on the way out. It is often used as a prank on drunk companions, who have a nasty surprise waiting for them the next time they go to relieve themselves.",
"Hair of the Bloodhound - Once you have become intoxicated on this brew, you gain the usual drawbacks of drunkenness but gain advantage on survival checks.",
"Seer's Solution - A mildly viscous green liquid. The first two shots have no effect. The third gives you truesight up to 60ft for 1d4 minutes. The fourth and subsequent shots give the drinker horrible audio/visual hallucinations for 1d4+2 hours. Counter resets at dawn.",
"Spider's Bite - Take 1d8 poison damage on a failed CON saving throw. Packs a mean punch.",
"The Fortnight - Very strong alcohol. If you actually drink enough to get drunk, you stay hammered for days.",
"Tinkerer's Tincture - dark and smooth, and when you drink it all the clicking, whistling, and scraping noises are more apparent to your ear.",
"2 Couples in a Shared Household - (much easier if teabags exist) Two different types of hot tea, 2 of each, into one mug.",
"Sucker Punching a Rabbit - A single teabag steeped in the biggest mug you have.",
"Buried Treasure - A single, very sweet, rather expensive hard candy is stuck to the bottom of a mug of very hard liqour. Once you've drunk it all, you get a spoon to pull it off with.",
"Ouch - Two full shots worth of lemon juice put into a glass of very high proof alcohol.",
"What was I Saying? - An unassuming shot of very strong alcohol, with a cherry in it, usually taken in the middle of a conversation, which is promptly ended.",
"Actual Torture - 2 Teaspoons of salt which are to be eaten all at once. Then washed down with a citrus based liquor. If anyone else offers any drinks, their hands are free game for attack.",
"The Green Kobold - The first drink to ever be served in a piece of ham, with the skin. 1 shot of herbal liquor wrapped in ham. To be eater all at once. Probably fixed in place with at least 1 pin, make sure you pick it out before you eat it.",
"End of the Line - Very high quality, rather expensive alcohol. A coin is flipped. If heads, your drink is free. If tails, you are forced to drink until you either die or pass out. If you regain consciousness, you must continue drinking.",
"Traffic Stop - Invented by a Diviner. Whenever a fight seems to be brewing, everyone orders a traffic stop. It's a mug of 3 separate liquors that stay separated in their mug, all very strong.The goal is to drink it all before the local police forces arrive.",
"Dragon Milk - not really milk, or related to dragons. It's an expensive white drink, resembling milk (duh) that removes any alcohol in your body. As a result you exale fire in the form of a single burp, resembling a dragon.",
"The Necromancer - a drink for those who fall unconcious from alcohol. It's a green glowing liquid. Also known as the 'Corpse Reviver'; when poured into the unconcious persons mouth he/she gets up and walks in a way similair to a zombie.",
"Beholder - a delicious drink decorated with an eye or multiple smaller ones. Feels like normal alcohol but gives the person a (false of course) feeling he/she has multiple eyes after drinking enough of it.",
"Elysium - a nonalcoholic drink that smells and looks as bad as it tastes. Some compared it to trash, vomit or even excrement but only because they couldn't find the adequate foul words. Most refuse to look at it, let alone allow it to come close to their nose. Only those with the strongest will manage to gulp it down. Once drunk, the person experiences true bliss, which seems to last for decades. In reality it's a few seconds.",
"Nine Steps - commonly known as 'The Niner' or by it's full name 'Nine Steps to Hell'. It is a liquid that when left to settle separates into 9 parts, the bottom one being pure black and the top a beautiful red with a gradient in between. After drinking it the person seems frozen for a few seconds, but to the person who gulpes it down it feels like days, weeks, maybe even months of 9 different experiences, all basically a form of torture. Often used as a torture method but sometimes drunk to prove ones mental strenght, as those that can't endure it go insane. The niner is a rare drink because it's extremely hard to make. An amateur making it, if the ingridients aren't correct to the milligram, makes a drink that causes instant death.",
"Honey Pine Dew - An imported halfling mead, served in small cups. Very pleasant taste, cheap in halfling towns, but expensive elsewhere.",
"Cubed Spirit - This drink is served as a hollow ice cube with liquid spirit within. As the ice melts in your mouth the drink will come out. How exactly this novelty drink is produced, is a well kept secret.",
"Milky Way Whisky - A light blue drink that tastes like very watered down, sweetened milk with a lot of alcohol. Besides giving a quick buzz, it also gives bone, and thus teeth, a blue fluorescent glow for 1d4 hours.",
"The house special - This drink doesn't have a particular name, but it's cheap. It doesn't really have an effect. In fact, you're pretty sure the bartender is simply casting prestidigitation on dishwater to make it raste like like it has alcohol in it.",
"True Dwarven Stout - A strong drink, not recommended if you cannot handle your alcohol. Traditionally served on the rocks, literally. There are pieces of stone lying on the bottom of your drink. Said to give the true mining flavor. This drink will make any dwarve feel very nostalgic.",
"Petralias Wine - A very expensive wine that is served as a single droplet. It does nothing for thirst or getting drunk, bit the flavor is said to be very concentrated and the lack of drink quantity should make the experience richer. Typically ordered by very pretentious people.",
"Golden Goat - Fermented goat milk and honey.",
"Star Liquid - A really black drink resembling the night sky. If you drink it you experience a wonderful journey trough the stars for 1 min.",
"Polymorphic Brew - Commonly used in drinking games, this brew will turn the user into an animal when they burp. They turn back about a minute later.",
"Insom's Ale - has same effects as a long rest, calming.",
"Lilphina’s Lusty Lover Liquid Liquor - The bottle comes in two parts, with each part having a different hue of color depending on the flavor. When two persons consume the drink within 5 minutes of one another, their minds are swapped for 1 hour.",
"Piña Colossus - a rare colossal pineapple hollowed out and filled with rum, coconut cream, and pineapple juice. Usually a shared drink. The pineapple shrinks in size when the liquid is drank or spilled. It will also continue to expand and grow to colossal proportions the more liquid that is added.",
"The Coup de Grace - At the end of the night, the bartop is wiped down with a rag, the contents are rung into a shot glass.",
"Drippzt - The drops in the bottoms of emptied kegs mixed together and dyed black. Anyone who can drink a pint of it without vomiting doesn’t have to pay.",
"Firebreath Ale - If someone drinks it and then breathes into a flame, a 3rd level Fireball is cast centered on the flame.",
"Belching rum - After trunking this make a con save. On a failed save the effect takes place immediately. On a success you choose when to have the effect take place (After ten minutes the effect takes place no matter what.) Effect: You belch thunderously. Everyone in a 100 foot radius is defened for one round.",
"The Titans brew - A regular tasting ale served in an enormous cup, and after drinking it the receiver grows a few inches.",
"Paladin’s Bane - sweet enough to tempt the righteous and you hardly taste the alcohol, but it’ll give you a decent hangover and diabetes to boot.",
"Goodberry Gin - if you drink enough of it, it works as a mild healing potion which may or may not compensate for the damage done to your liver or you falling down the stairs while drunk. 1d6 hp healing, 1d4 drunk damage.",
"Hagraven Brandy - though it has a taste as ugly as its namegiver, the appearance of everyone around you will exponentially improve with every sip you take. -3 on Charisma saving throws for 1d6 hours.",
"Will-o-the-Whiskey - whisky with minor hallucinatory effects, starts with a tiny tingling light in the corner of your eyes, ends with a shining orb of light dancing a few yards away from you, moving away as you try to catch it.",
"Mandrake Mocha - a hot creamy beverage with a narcotic effect. Dulls the pain, leads you into a deep slumber.",
"Madman’s Mead - downing a mug causes a fleeting bout of insanity, roll a d100 for effects of Short-Term Madness.",
"Ochre Stout - a cheap drink so thick you can taste chunks in it. Best to swallow and not be curious.",
"The Drunken Dwarf - a pint of dwarven stout with a teabag in it.",
"For (local deity)’s Sake - a local sake or rice wine, popular with priests.",
"Ciderella - a sweet apple cider, considered “a girls drink”. Even the toughest bloke will begin giggling like a little girl after a few drinks.",
"Jalapálinka - a fruit brandy spiced with hot peppers. Burns the throat, downing a pitcher leads to steam escaping ears and nostrils.",
"Ginger Ale - Wait, this doesn’t taste like ginger at all... An ale that turns your hair ginger, effect lasts for 1d6 days.",
"The Maiden’s Ass - a quadrupel beer, served in a bottle with a donkey and a pretty girl on the label. Sweet but strong.",
"Bock Bear - a bock beer that gives you +1 Str and extra body hair for 1d6 hours.",
"Polypilsener - turns you into a canary for 1d4 minutes. Drinking half a mug will turn you halfway into a canary.",
"Our Thoughts and Prayers - a brandy that works as a reverse Detect Thoughts spell; surrounding people learn your surface thoughts, although you’re unaware of it. Range increases with 2ft each glass, though your thoughts don’t exactly get more coherent.",
"Smirgnome - a vodka that fills your brain with the weirdest ideas, although the morning after you’ll likely have no memory of inventing a sunlight-storing clockwork pigeon to hunt vampires with.",
"Abbathor’s Gold - a clear golden mead that does nothing to quench your thirst - instead, you crave more of it. Roll a Charisma saving throw (DC 10) after each glass; if you fail, you keep drinking. After 8 glasses you pass out for 1d10 hours.",
"Coala - a Dwarven invention, this black bubbly drink tastes like grinded coal with sugar, but also makes you feel reinvigorated and less tired.",
"Cinder - a spiced cider served hot. You can control non-magical flame that fits within a 1ft cube for 1d10 minutes.",
"The Umber Hulk - a pint of whisky, brandy and tequila in equal measures. Good luck.",
"Bottomless pint - the bartender pours beer into a ceramic mug. When the patron pulls the glass up to their mouths, they realize that the mug really doesn’t have a bottom. The mug is empty, and the beer has been pour through the mug into a hole in the bar with a pitcher underneath.",
"Copperhead - the bartender pours a beer, mixes in a shot of whiskey, and then a couple drop of snake venom from a vial. Normally drinkers will feel numb in their extremities. If a drinker fails their saving throw, they will be paralyzed from the neck down for 1D20 minutes.",
"Brazenbrew - Served in a special mug laced with bronze, the drinker is more apt to make outrageous claims of ability, but also gains the relevant luck to succeed while still under the influence.",
"Yam's Choice - A delightful mead, high class, has a fair chance of being extremely addictive. Withdrawal is applying two effects from the long-term madness chart, and one from the short-term chart.",
"Witchwood Absinthe - A potent spirit the color of a moss-covered tombstone. It has mild hallucinogenic properties, and local folklore holds you can hear the voices of those you've lost if you drink enough. Not too much, though. You might join them.",
"Salty Dog Ale - A dark, rich brew that reminds you of the sea. Plopping in the shell of a sea snail for good luck is customary, and adds a fitting salinity to the drink.",
"Hymvaren's Luck - A bright, golden-colored beer named after a local drunk who woke up on the beach after a night of carousing with a chest full of pirate's treasure. He claims to have no memory of that night.",
"Bourbon of Dwarfkind - makes the user start to grow a beard. If they can normally, you see accelerated growth. If they can’t, a few hairs will sprout on their chin.",
"Old Mill Rye - tastes alright, has a strange aftertaste in the back of your throat of an old sock. It's cheap and gets you drink",
"[Insert local diety's name] brew - Has characteristics that reminds you of said god. Gold for sun worship for example. Hint of cinnamon for a hot and fiery one. A hint of licorice root perhaps",
"Ochre Jelly Ale - Ale with safe-to-drink ochre jelly mixed in it.",
"A regular glass of water - That’s it. It’s just a normal glass with regular, boring water inside.",
"Mimic Drink - Usually sold by tricksters to play pranks on people. Looks like a regular glass of water, but a tiny water elemental/water weird is disguised as normal water.",
"Liquid Nitrogen - Drank by frost giants and other beings that can tolerate extreme cold.",
"Mead of invulnerability - Once drunk user makes a DC 15 Wisdom check. On a fail believes they are immune to all damage and if damage is dealt to them believe they did not take the damage. Effects for ten minutes. User still take all damage as normal.",
"Inverted rum - when you drink it, every one around you in a 15 foot cube becomes drunk. This dose not include yourself.",
"Goblin Spit - whiskey and gin mixed with the barkeep's home-made mints. It tastes surprisingly good despite its name. As is tavern tradition, a long-distance spitting competition occurs after every round.",
"The Hook and Slider - a cooked goat (?) intestine tied and filled with a heavy beer. After finishing the beer chow on the intensive",
"Lucky Leprechaun - A sickly green drink that gives you advantage on Charisma checks for one hour.",
"The Tiamat - 5 different shots, one for each color of the different heads. One is black and syrupy, one blue and gives tingly feeling, one is on fire, one is green and tastes a bit minty, the last is white and frosts the closest things. They are mixed together and separate in the cup making a very nice presentation.",
"The Sweet Roll - flavors of cinnamon and sugar blend with the strong scent of rum. The drinker gains an additional 1d4 to any pickpocket attempts for the next hour.",
"The Sailor's Spirit - There once was a cap' and a crew, Who made the most wonderful brew, From rations of lime, They would in their spare time, Make fine drinks no man could outdo.",
"Good Hearth's Brew - A hot spiced rum which is popular during long winter nights for the immediate feeling of warmth and calm that follows.",
"Tarnation - A strong spiced cider served warm and traditionally drank as quickly as posible after a boisterous cheer or a lewd drinking song. Enchantmented with the effect of the consumer belching a small flame right after ingesting.",
"Gnome Rum - Makes your voice high, squeaky, and annoying.",
"Ethereal Ale - The more intoxicated you get, the more you fade into the ethereal plane. First you become slightly transparent, than objects start to phase through you from tame to time and if you manage to keep drinking you entirely enter the ethereal plane.",
"Blood Wine",
"Honeywine",
"Haraleven White",
"Dragondew White",
"Bitterthorn Dry",
"Blood of the Raven",
"Feather Wine",
"Elven Wheat-Wine",
"Nelf Thalor Crush",
"Amenathas Red",
"Hefsari White",
"Emberberry Dark",
"Figdale Red",
"Rosewood Vintage",
"Delmen Wine",
"Ellholone Crush",
"Malorian White",
"Starglen White",
"Foxmantle Crush",
"Theenalion Rose",
"Berdusk Red",
"Goblin Wine",
"Namarie Dark",
"Khaluma Rose",
"Ogre Blood",
"Fog-King’s Mist",
"Golden Touch",
"Glowfire Dry",
"Saluna Wine",
"Dawnrim Rose",
"Spiderdark Venom",
"Surinen Dry",
"Stoneblood Red",
"Kana Nalore Nectar",
"Dragon’s Tears",
"Deepwine",
"Wild Spellsap No. 4",
"Laurie Lantar Champagne",
"Old Empire No. 3",
"Manycherry Wine",
"Gnomish Oil",
"Demon’s Piss",
"Ilnelond Rose",
"Dwarven Tomb",
"Celestial Wind",
"Nyalume Nectar",
"Kea Ennore Crush",
"Wintermead",
"Arlgroth Wine",
"Gorgon Claret",
"Frost Giant’s Kiss",
"Tintilar Wine",
"Frostmind Wine",
"Elderblossom Rose",
"Runeshine",
"Salabelle Shadow",
"Rootweal",
"Eastgate Ruby",
"Nightsky Vintage",
"Wave Thalor Shadow",
"Belet Champagne",
"Moonlit Wine",
"Diamondfire Vintage",
"Frostfar Ice Wine",
"Eshna Tirion Red",
"Wintervine Wine",
"Wasebel Wine",
"Andune Dry",
"Miruvore",
"A’vethemar Crush",
"Ashnerius Rose",
"Troll’s Blood",
"Purple Grapemash No. 2",
"Spellshine Wine",
"Filfa Alari Nectar",
"Silranlond Dry",
"Gardell Red",
"Assassin Wine",
"Celestial Wine",
"King’s Vintage",
"Aboleth Blood",
"Nese Belanore Wine",
"Starqueen Red",
"Redroot Red",
"Awakened Wine",
"Soulsliver Rose",
"Blue Dragon Dark",
"Firedrake Red",
"Stella’s Blessing",
"Crowberry Wine",
"Grun'mel's Claret",
"Daggerdrink Special",
"Colas Rosato",
"Sel'bin Dark",
"Sunshine Sap",
"O’al Alora Ruby",
"Dragon’s Breath",
"Mintmore Nectar",
"Spellkeep Special",
"Shadowfel Sap"
]
